# Exercises


# Module 1

### Problem 1

You are given the following data describing final grades in a tricky statistics course. There were 20 A's, 97 B's, 163 C's, 76 D's, 31 E's and 13 F's.

a)  What are the most and least common grades?

b)  Organize this data in a frequency table

c)  Find the relative frequency of each grade

d)  What proportion of students failed the course?

e)  What proportion of students got a B or above?

f)  What proportion of students got between a C and an E?

<details>

<summary>Show solutions</summary>

a)  The most common grade is C with 163 instances, and the least common grade is F with only 13 instances.

b)  The table can be organised like this for instance:

| **Grade**     | **Number**      |
|---------------|-----------------|
|A              | 20              |
|B              | 97              |
|C              | 163             |
|D              | 76              |
|E              | 31              |
|F              | 13              |

c)  By summing the amount of respective registered grades we find that there are 400 total. We can now divide the number of instances for each grade by the total of 400 to find the relative frequency. For example, we have 20 instances of A's out of 400 total grades.

$$\frac{20}{400}=0.05$$

We can repeat this for all grades and add to the existing table:

|**Grade**      | **Number**      | **Frequency**      |
|---------------|-----------------|--------------------|
|A              | 20              | 0.05               |
|B              | 97              | 0.2425             |
|C              | 163             | 0.4075             |
|D              | 76              | 0.19               |
|E              | 31              | 0.0775             |
|F              | 13              | 0.0325             |




d)  The only failing grade is F. We can read from the new table that this we have 0.0325 or 3.25% of students that failed this course.

e)  To find out what proportion of students got a B or above we need the cumulative frequency. We find this cumulative frequency by summing thge relative frequency of all the relevant cases. In this case "B or above" is the same as achieving a B or an A. The relative frequency of B's is 0.2425 and for A's it's 0.05.

$$ 0.2425+0.05=0.2925=29.25\%$$

f)  To find out what proportion of students got grades between C and E we also need to find the cumulative frequency. Like in e this requires summing the appropriate relative frequencies. From the table in b we can see that the respective relative frequencies are 0.4075 for C, 0.19 for D and 0.0775 for E.

$$ 0.4075+0.19+0.0775=0.675=67.5\%$$

Alternatively we can take note of the fact that we already know the proportion of students that were below this grade range (the proportion of F's), as well as the proportion of students that scored above this range (the proportion that scored B or above). By subtracting the proportion of students that scored outside this range from 1 (100%), we should arrive at the same answer.

$$1-0.0325-0.2925=0.675=67.5\%$$

</details>

### Problem 2

You hear that the average starting salary after finishing a master's degree at NHH is NOK 550 000, the median salary is NOK 525 000, and the mode is NOK 500 000. What can you infer from this?

<details>

<summary>Show solutions</summary>

Though they might seem similar on a surface level, the mode, median and mean give slightly different information.

The mode tells us what the most common observation in the data is. In our case this means that the **most common** starting salary after graduating with a master's degree from NHH is NOK 500 000.

The median is the "middle value" in the dataset, meaning that 50 percent of the observations should be below this value, whilst the other 50 percent should be above this value. In our case it means that half of graduates will have a starting salary that's NOK 525 000 or below whilst the other half get a starting salary of NOK 525 000 or above.

Finally, the mean reflects the **average** of the dataset. We can tell here that the average is NOK 550 000. Additionally, by looking at everything in context we can also make some minor inferences. We see that the mean is higher than the median, indicating that some datapoints are skewing the average upwards, i.e. some graduates are earning really well compared to their peers from the get go. Additionally we see that the mode is 500 000, compared to the mean of 550 000. As the mode is the most common observation and is below the median, this seems to suggest that those who end up with a higher starting salary start with a substantially higher one compared to their peers, for the average to skew above the median.

</details>

### Problem 3

At a retail chain Floormart the Median pay by hour is \$25, but the average is \$33 per hour. What does this suggest?

<details>

<summary>Show solutions</summary>

Similar to in Problem 2, the indication here seems to be that some employees may be earning significantly more than others. Exactly how many employees are earning more and by how much is impossible to tell given our available information, but it seems likely that the executives or managers and above may have significantly higher pay than most employees in Floormart. These few employees having a much higher pay than for instance new hires or other low level workers could explain this disparity.

</details>

### Problem 4

If possible, find the mode, median and mean of the following set of dice rolls 

$$4,6,5,5,6,2,1,6,3,6,2,1,3$$

<details>

<summary>Show solutions</summary>

The mode is the most common observation. As 6 appears 4 times here, more than any other roll, 6 is the mode.

To clearly find the median we can sort the data from lowest to highest observation. We then end up with {1,1,2,2,3,3,4,5,5,6,6,6,6}. We have 13 observations here, so the median will be given by the 7th observation from the bottom. In our case we find that 4 is the median.

Finally we can find the mean by taking the average of the observed rolls.

Recall the formula for averages is

$$\overline{X}=\frac{1}{n}\sum_{i=1}^{n}X_i$$

In our case we can just sum each obvservation and divide by the number of observations, which is 13.

\begin{align*}
\overline{X}&=\frac{1}{13}(1+1+2+2+3+3+4+5+5+6+6+6+6)\\
&=\frac{50}{13}\approx3.846
\end{align*}

</details>

### Problem 5

If possible, find the mode, median and mean of the following set of favorite colors 

red,blue,blue,green,yellow,green,green,blue,red,red,pink,purple,blue

<details>

<summary>Show solutions</summary>

The mode is found by finding the most common observation. Here "blue" is the most common favourite color, with 4 instances, and thus "blue" is our mode.

It is not possible to find a median within this data, as we need to be able to logically sort the data to be able to have a meaningful median. I.e. as the data is not ordinal, we can't find a median.

It is not possible to find a mean from this data. We need numerical data to be able to give a meaningful mean.

</details>

### Problem 6

What level of data is required to find modes, means, and medians? (Categorical, ordinal, etc.)

<details>

<summary>Show solutions</summary>

To find a mode we need at least categorical data.

To find a median we need data that is ordinal.

To find a mean we need data that is numerical.

</details>

### Problem 7

You get the dataset 
$$1,1,1,1,1,3,3,3,3,7,7,7,7,9,9,9.$$

a)  Find the mode, median and mean of the above set.

b)  Find the the first and third quartile of the set.

c)  What are the 0th and 100th percentiles of the set?

d)  Would the median change if you were to add a single datapoint of 11 to the set? What would the median of the new set be? What if we were to add two datapoints of 11?

<details>

<summary>Show solutions</summary>

a)  The most common observation is 1, thus the mode is 1. We have an even number of observations in this set, 16.

By taking the average of the two middlemost values we will find the median. Both the 8th and 9th value in the set are 3, and thus the median of the set is 3.

We can find the mean by taking the average of the data.

\begin{align*}
\overline{X}&=\frac{1}{16}(1+1+1+1+1+3+3+3+3+7+7+7+7+9+9+9)\\
&=\frac{72}{16}=4.5
\end{align*}

b)  The first quartile indicates that 25% of observations should be below this threshold. In our case we see that the first quartile would fall between the 4th and 5th observation, which are both 1, telling us the 1st qaurtile is 1.

The 3rd quartile indicates that 75% of observations should be below it. The 12th and 13th observations are both 7, letting us know that the third quartile is 7.

c)  The 0th percentile indicates the minimum value of the set while the 100th percentile indicates the maximium value. We can then say that the 0th percentile is 1 and the 100th percentile is 9.

d)  If we add a datapoint of 11 to the set, we would now have 17 observations, meaning that the 9th observation from the bottom would indicate the median. The 9th observation from the bottom is 3, which is the same median as in the previous case, so the median would not change. If we were to add two datapoints of 11 to the set, we would have 18 observations. With 18 observations we have to take the average of the two middlemost observations after sorting. The two middlemost observations are the 9th and 10th ones from the bottom, meaning 3 and 7. The average would then be:

$$\frac{1}{2}(3+7)=\frac{10}{2}=5$$

The median in this case would be 5, so it would indeed change from the previous case.

</details>

### Problem 8

You get this dataset of a group of 11 people and their respective heights in centimetres. 

$$184,157,168,172,198,154,192,161,186,177,165.$$

a)  Find the mean/average height of this group.

b)  Find the variance in height in this group and the standard deviation.

c)  Does the variance and standard deviation seem big, small or somewhere in between in this context?

d)  What would be the effect on the variance of adding another person to the sample that is of the average height we found in a. Would the variance increase, decrease or stay the same?

e)  What would be the effect of adding another person to the group that's 200cm tall. Would the variance increase, decrease or stay the same? Why is the change intuitive?

f)  What would be the effect of adding another person to the group that's 140cm tall. Would the variance increase, decrease or stay the same? Why is the change intuitive? Why is the change in variance here greater than the one in e.?

<details>

<summary>Show solutions</summary>

a)We sum our observations, and divide by 11, which is the number of observations.\

\begin{align*}
\overline{X}=\frac{1}{11}(&184+157+168+172+198+154+192+161 \\ &+186+177+165)=\frac{1914}{11}=174
\end{align*}

b)  Here we need to first recall the formula for variance.

$$S_X^2=\frac{1}{n-1}\sum_{i=1}^{n}(X_i-\overline{X})^2$$

We recall that the mean we found in a is 174 and that we have 11 total observations. Now we have everything we need to plug in our data and find the variance.


\begin{align*}
S_X^2&=\frac{1}{11-1}\bigg((184-174)^2+(157-174)^2+(168-174)^2 \\ &+(172-174)^2+(198-174)^2+(154-174)^2+(192-174)^2+(161-174)^2+ \\&(186-174)^2+(177-174)^2+(165-174)^2\bigg)=\frac{2132}{10}=213.2
\end{align*}


Now we only need to find standard deviation.Recall that the standard deviation is the square root of the variance.

$$S_X=\sqrt{S_X^2}=\sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(X_i-\overline{X})^2}$$

In our case we need only plug in the variance we have already found.

$$S_X=\sqrt{213.2}\approx14.6$$

c)  Variance is hard to interpret directly, but the standard deviation is very simple. The standard deviation tells us that the average absolute difference from the mean in our data. Here we see that the standard deviation is 14.6cm, so on average the people in this group are 14.6 away from the the mean in terms of height. This means the we would expect a random person from this group to be either about 159cm tall or 188cm tall. It's not all that simple to say if this is a lot or not, that depends on the data collected. If this is a sample from a group of Norwegian men age 20, this could seem like a very big standard deviation and variance. However, if this is a group of men and women with an age range from 14 to 35, this might not seem like such a big variance.

d)  If we were to only add more people of the average height we found (174cm) the variance would decrease. There are two effects in play here. The when we add more observations our n gets bigger, and thus we divide by a larger number, but we also have to add another squared difference from the mean. In this case we add another observation that's exactly equal to the mean. Firstly what effect will this have on the mean itself? Intuitively, the mean will **not** change in this case. Notice that the squared difference between the mean and itself is 0.

$$(\overline{X}-\overline{X})^2=(174-174)^2=0^2=0$$

Let's now add this to our equation for variance. Since we have one more observation we will be dividing by (n-1)+1=n, instead of n-1.

\begin{align*}
S_{X1}^2&=\frac{1}{n} \left(\sum_{i=1}^n(X_i-\overline{X})^2+(\overline{X}-\overline{X})^2\right)
    =\frac{1}{n} \left(\sum_{i=1}^n(X_i-\overline{X})^2+0\right)
    \\&=\frac{1}{n} \left(\sum_{i=1}^n(X_i-\overline{X})^2\right)
    <\frac{1}{n-1} \left(\sum_{i=1}^n(X_i-\overline{X})^2\right)=S_X^2
\end{align*}

**For those that don't find it intuitive that the mean stays the same when you add more observations the equal the mean:**

Underneath I have shown algebraically what happens to the mean when you add **one** more observation in the sample that equals the mean. This can easily be extended to adding any number, **m**, more observations (try for yourself!).

\begin{align*}
\overline{X}_1&=\frac{1}{n+1} \left( \sum_{i=1}^{n}X_i+\overline{X} \right)=\frac{1}{n+1}\left( \frac{n}{n}\sum_{i=1}^nX_i+\overline{X} \right) \\ &=\frac{1}{n+1}\left(n\overline{X}+\overline{X}\right) = \frac{n+1}{n+1}\overline{X}=\overline{X}
\end{align*}

Now, let's see what happens to the variance, when we add another observation that equals the mean.

$$S_{X1}^2= \frac{1}{n-1+1}\left(\sum_{i=1}^n(X_i-\overline{X})^2+(\overline{X}-\overline{X})^2\right)$$

e)  We can amend our data by adding the new observation of 200cm, and with this we can compute the new mean and variance. We will notice that since we add an observation that is higher than the average, the mean will increase, and we will also find that the variance (and consequently the standard deviation) will both increase. The new values will be:

$$ \overline{X}\approx176.17 \\ S_X^2\approx250.15$$

The intuition is simply that since our new observation is very different from our mean, the variance will increase. Adding the new squared difference has a greater effect than dividing by a higher number. Recall that our original mean was 174 and our original standard deviation was approximately 14.6. This means that the average absolute difference between an observation and the mean is about 14.6.

$$|200-174|=26>14.6$$

This means that by adding this new observation, since it's difference from the mean is so clearly much greater than the standard deviation, the standard deviation should increase by adding this observation. When the standard deviation increases, so will the variance. (Note that we can only intuit in this way when the absolute difference between the new observation and the mean is quite a bit greater than the standard deviation. The intuition you should build from this is that new observations that are **very different** from the mean will **increase** the variance, and consequently, observations that are **close** to the mean will **decrease** the variance.)

f)  This case is very similar to the one in e. The only notable difference is that we add an observation that is much **lower** than the mean, rather than one which is much **higher**. Computing the the new mean and variance we get:

$$\overline{X}\approx171.17 \\ S_X^2\approx290.15 $$

The intuition here is exactly the same as in e. Since the new observation is very different from the mean, the variance should increase. Let's compare the absolute difference between the mean and the new observation to the standard deviation.

$$|140-174|=|-34|=34>14.6$$

From this it should also be clear why the change in variance here is greater than the one in e. Since 140 is an observation that is **farther away** from the mean (174), than 200, the increase in variance will be greater.

(**Extra challenge for those that can't get enough**: Can you intuit what would happen in an opposite case? Would the variance change more if we added if we added a new observation of someone that was 177cm tall or with someone that was 172cm tall?)

</details>

### Problem 9.

Recall the variance and standard deviation found in Problem 8b. Imagine that instead of the height of people, the variance and standard deviation was instead found from data on height of trees (Note: the collected data is not necessarily the same even though the variance is the same). Does the variance and standard deviation feel big, small or somewhere in between in this context?

<details>

<summary>Show solutions</summary>

This problem is mainly about interpretation, but let's consider the standard deviation. We have a standard deviation of 14.6cm. A height difference of 14.6cm between two **people** is quite large, and very noticeable. When it comes to trees, however, that is not necessarily the case. Short trees can be as short as just a few centimeters, where as the tallest trees can reach upwards of 100 meters(!). Even without considering the shortest and tallest trees, we find that there can easily be several meters of difference between completely ordinary trees. Since we only know that we are working with trees in this case, it's hard to assume anything about the data, but looking at the standard deviation we can tell that these trees must be **very similar** in stature as far as trees are considered. If anything, this variance, that seems quite reasonable (or even very large), when we consider the heights of people, seems completely minuscule when we consider trees instead. It's impossible to say whether variance and standard deviation is large or small with no context, as is illustrated with this comparison.

</details>

### Problem 10

In what scenario would we get a Variance of 0?

<details>

<summary>Show solutions</summary>

For the variance to be 0, our observations simply can't vary. This means that all observations have to have the same value.

This can be shown algebraically. Let all observations $X_i=X$ be equal. Then
$$\overline{X}=\frac{1}{n}\sum_{i=1}^nX_i=\frac{1}{n}\sum_{i=1}^nX=\frac{n}{n}X=X $$

It's clear that all observations here are equal to the mean, which gives us.

\begin{align*}
S_X^2&=\frac{1}{n-1}\sum_{i=1}^n(X_i-\overline{X})^2=\frac{1}{n-1}\sum_{i=1}^n(\overline{X}-\overline{X})^2 \\ &=\frac{1}{n-1}\sum_{i=1}^n0=\frac{0}{n-1}=0
\end{align*}

By looking at the equation for the variance, we can tell that if **any** one or more observations were to deviate from the mean, there would be variance in our data.

</details>

### Problem 11

You have a dataset with six observations and a mean of 50. Show that when you have any observations outside of the interval \[45;55\] the variance will always be greater than 5.

<details>

<summary>Show solutions</summary>

We have received this information:

$$n=6, \ \overline{X}=50$$

To show that that our variance will always be greater than 5 when we have an observation **outside** of the given interval, let's consider the situation that would create the **least** variance. Consider a situation where only **one** observation is 55, and the rest of the observations have to make up for this by all of them being a bit less than 50. Since we use squared sums when we compute the variance, we would get the least variance from the 5 last observations being equally close to to the mean. We can use an equation to find out what each of these 5 observations have to equal. For this we use the formula to calculate an average.

$$\overline{X}=\frac{1}{n}\sum_{i=1}^nX_i$$

Since we know that the average we're looking for is 50, **one** observation is 55 and the last 5 observations are equal, we get an equation with one variable.

\begin{align*}
50&=\frac{1}{6}(5X+55) \\
\Rightarrow 6\cdot 50&=5X+55 \\
\Rightarrow 300&=5X+55 \\
\Rightarrow 300-55&=5X \\
\Rightarrow 245&=5X \\
\Rightarrow X&=49
\end{align*}

Now we have a clear view of the data that would give the minimum variance. {49,49,49,49,49,55} Finally, we can compute the variance.

\begin{align*}
S_X^2&=\frac{1}{6-1}\left(5(49-50)^2+(55-50)^2 \right) \\
&=\frac{1}{5}(5\cdot(-1)^2+5^2)=\frac{1}{5}(5+25) \\ 
&=\frac{30}{5}=6>5
\end{align*}

</details>


### Problem 12
You are given the following dataset containing information about survival of people travelling on the Titanic in 1912. The data contains counts of how many who survived or not of groups by ticket class, sex, age (child/adult). Can you categorize the columns based on whether they are categorical, numeric, binary, integer or real?

```{r, echo = FALSE}
data("Titanic")
titanic_data <- as.data.frame(Titanic)
knitr::kable(head(titanic_data,10))
```

<details>

<summary>Show suggested solutions</summary>

-   Class: Categorical, although could be treated as ordinal (1st \> 2nd \> 3rd \> Crew)
-   Sex: Binary (Male/female)
-   Age: Binary (Child/adult)
-   Survived: Binary (no/yes)
-   Freq: Numerical, integer.

</details>
