# Random number generation

::: {style="padding:56.25% 0 0 0;position:relative;"}
<iframe src="https://player.vimeo.com/video/1054272069?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Random Number Generation">

</iframe>
:::

```{=html}
<script src="https://player.vimeo.com/api/player.js"></script>
```

Slides for ["Random number generation"](video-pdfs/3/random_number_generation.pdf)

## Control questions

1.  What is random?
2.  What do we call random numbers generated from an algorithm?
3.  Are these numbers truly random?
4.  What do mean when we say that numbers generated by the algorithms are deterministic?
5.  What does a setting a seed do?
6.  Can you explain the inverse transform sampling procedure?

## Generate random numbers from a distribution

```{python}
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Generate 2000 random numbers from a uniform distribution: 
x = stats.uniform.rvs(size = 2000)
# Plot histogram of the simulated data: 
sns.histplot(x, stat = "density")
plt.show()
# Add uniform density function to the plot:
sns.histplot(x, stat = "density")
xvalues = np.linspace(0, 1, 2000)
pdf = stats.uniform.pdf(xvalues)
plt.plot(xvalues, pdf, color = "red")
plt.show()
```

It is often a good idea to set a seed when generating random numbers. This has the benefit that every time you rerun your code, the same random random are generated. If you want a new draw from the distribution, you change the seed and you will get a new set of numbers. Test this out your self using the code below:

```{python}
np.random.seed(123)
x = stats.uniform.rvs(size = 5)
print(x)
np.random.seed(123)
x = stats.uniform.rvs(size = 5)
print(x)
np.random.seed(124)
x = stats.uniform.rvs(size = 5)
print(x)
```
