# Exercises

## One-sample t-test
For the following exercises, we will use the test statistic for one-sample t-test with null hypothesis $H_0:\mu=\mu_0$:
$$T=\frac{\bar x-\mu_0}{s/\sqrt{n}},$$
where $n$ is the sample size, $\bar x$ is the sample mean, $s$ is the sample standard deviation and $\mu_0$ is the expected value under the null hypothesis. 

### Problem 1.1
A company selling premium coffee beans wants to determine whether reducing the price of its product leads to a significant increase in the average number of bags sold per day. The marketing team conducted a test by lowering the price for a month in select stores and measuring the sales volume. They want to analyze whether the mean daily sales after the price reduction are significantly higher than before.

a) Set up the null- and alternative hypothesis, and decide on a suitable significance level. 

Before the price reduction, the mean daily sales were 200 bags. After the price reduction, a sample of 30 days of sales data showed a sample mean of 215 bags, with standard deviation 25 bags. 

b) Calculate the test statistic. 

c) Find the p-value. What is the conclusion?


<details>
<summary>Show solutions</summary>
a) $H_0: \mu\le 200$ vs $H_1: \mu>200$. We could allow for a relatively high significance level in this context, because rejecting a true null hypothesis (Type I error) will most likely not have large consequences, e.g. $\alpha =0.1$. 

b) $T=(215-200)/(25/\sqrt{30})=3.29$

c) $\text{p-value}=P(T_{29}>3.29)=0.00132$. The p-value is very low, indicating that we may reject the null hypothesis at (almost) any significance level in (a). The company should continue with the reduced price.
```{python}
from scipy import stats
print(1-stats.t.cdf(3.29, 29))
```

</details>

### Problem 1.2
A large company is trying to encourage employees to save more for retirement. Previously, employees had to actively sign up for the company's pension savings plan (opt-in system). Recently, the company changed its policy so that employees are automatically enrolled in the plan but can opt out if they wish (opt-out system). Behavioral economists suggest that default options strongly influence decision-making, leading to higher participation rates in savings plans.

The HR department wants to test with a significance level of 5\% whether the average monthly contribution to the retirement plan has increased significantly after implementing the opt-out system.

a) Set up the null- and alternative hypothesis.

Before the change, the average monthly contribution was \$250 per employee. After the policy change, a random sample of 50 employees showed: Sample mean of \$270 and standard deviation of \$90.

b) Calculate the test statistic. 

c) Find the p-value. What is the conclusion?


<details>
<summary>Show solutions</summary>

a) $H_0: \mu\le 250$ vs $H_1: \mu>250$. 

b) $T=(270-250)/(90/\sqrt{50})=1.57$

c) $\text{p-value}=P(T_{29}>3.29)=0.0613$. The p-value is higher than 5\%, indicating that we may reject not the null hypothesis. The pension payments have not increased due to the change from opting in to opting out.

```{python}
from scipy import stats
print(1-stats.t.cdf(2.94, 49))
```
</details>

### Problem 1.3
A nutritionist wants to test whether a new diet plan leads to a significant reduction in average daily calorie intake. A sample of 40 individuals followed the diet for one month, and their average daily calorie intake was recorded. 

The recommended daily intake before the diet was 2200 kcal. After one month, the sample had a mean intake of 2100 kcal with a standard deviation of 250 kcal.

a) Set up the null- and alternative hypotheses.

b) Calculate the test statistic.

c) Find the p-value and interpret the result.

<details>
<summary>Show solutions</summary>
a) $H_0: \mu\geq 2200$ vs $H_1: \mu<2200$.

b) $$T=\frac{2100-2200}{250/\sqrt{40}}=-2.53$$

c) $$\text{p-value}=P(T_{39}<-2.53)=0.0079$$

Since the p-value is lower than the conventional 5% significance level, we reject the null hypothesis, suggesting that the new diet plan significantly reduces daily calorie intake.

```{python}
from scipy import stats
print(stats.t.cdf(-2.53, 39))
```
</details>

### Problem 1.4
A smartphone manufacturer wants to determine whether the battery life of their new model is significantly different from the advertised 24 hours. A sample of 50 devices was tested, showing a mean battery life of 23.5 hours with a standard deviation of 1.2 hours.

a) Formulate the hypotheses.

b) Compute the test statistic.

c) Determine the p-value and state your conclusion.

<details>
<summary>Show solutions</summary>

a) $H_0: \mu=24$ vs $H_1: \mu\neq 24$.

b) $$T=\frac{23.5-24}{1.2/\sqrt{50}}=-2.946$$

c) $$\text{p-value}=2 \times P(T_{49}<-2.94)=0.0049$$

Since the p-value is very small, we reject the null hypothesis, indicating that the battery life is significantly different from 24 hours.

```{python}
print(2*stats.t.cdf(-2.946, 49))
```
</details>


## Two-sample t-test
For the following exercises, we will use the test statistic for two-sample t-test with null hypothesis $H_0:\mu_1=\mu_2+d_0$:
$$T=\frac{\bar x_1-\bar x_2-d_0}{\sqrt{s_1^2/n_1+s_2^2/n_2}},$$
where $n_1$ and $n_2$ are the sample sizes of the two samples, $\bar x_1$ and $\bar x_2$ are the sample means, $s_1$ and $s_2$ are the sample standard deviations and $d_0$ is the difference in expected value under the null hypothesis (often $d_0=0$). The test statistic follows a t-distribution with degrees of freedom (df): 
$$\text{df}=\frac{\big(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}\big)^2}{\frac{(s_1^2/n_1)^2}{n_1-1}+\frac{(s_1^2/n_2)^2}{n_2-1}}$$

### Problem 2.1
An e-commerce company wants to test whether showing customer reviews on product pages increases the average number of purchases. Behavioral economics suggests that social proof (i.e., seeing others' positive experiences) influences decision-making and can lead to higher sales.

To test this, the company randomly selected two groups of products: one group displayed customer reviews, and the other did not. They then compared the average daily sales per product between the two groups.

a) Set up the null- and alternative hypothesis. Use 10\% significance level. 

b) Discuss how the test statistic will behave under the various hypothesis. 

The experiment result in the following data:

- *Products with reviews*: Sample mean daily sales = 120 units, Sample standard deviation = 30, Sample size = 40
- *Products without reviews*: Sample mean daily sales = 105 units, Sample standard deviation = 28, Sample size = 40

c) Calculate the test statistic and the degrees of freedom.

d) Find the p-value. What is the conclusion?


<details>
<summary>Show solutions</summary>

Let $\mu_1$ be the expected daily sales with reviews and $\mu_2$ without reviewes. 

a) $H_0: \mu_1\le \mu_2$ vs $H_A: \mu_1>\mu_2$. 

b) Under the null hypothesis, we expect the numerator of the test statistic to be close to zero, making the test statistic close to zero. Under the alternative hypothesis, we expect $\bar x_1>\bar x_2$ such that the numerator of $T$ will be positive. Higher values will therefore favor the alternative hypothesis. 

c) 
```{python}
import numpy as np
s1 = 30;  s2 = 28; n1 = 40; n2 = 40
m1 = 120; m2 = 105;
df = (s1**2/n1 + s2**2/n2)**2/((s1**2/n1)**2/(n1-1)+(s2**2/n2)**2/(n2-1))
t = (m1-m2)/np.sqrt(s1*s1/n1+s2*s2/n2)
print("df=",df)
print("T=",t)
```

$T=(102-105)/\sqrt{30^2/40+28^2/40}=-0.462$
$$\text{df}=\frac{\big(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}\big)^2}{\frac{(s_1^2/n_1)^2}{n_1-1}+\frac{(s_1^2/n_2)^2}{n_2-1}}$$


d) $\text{p-value}=P(T_{29}>0.462)=0.32$. The p-value is lower than 10\%, indicating that we may reject the null hypothesis. There is enough evidence to suggest that the reviews increase the sales at a 10\% significance level. The company should show reviews of their products to increase sales. 

```{python}
from scipy import stats
print(1-stats.t.cdf(t, df))
```
</details>

### Problem 2.2
A company is testing whether offering a performance-based bonus increases employee productivity. They implement a new bonus system in one office location (Group A), while another office continues without bonuses (Group B). After three months, they measure the average number of completed sales calls per week in both offices. The company wants you to determine if the bonus system leads to higher productivity (mean number of sales calls).

a) Formulate the hypothesis problem including $H_0$, $H_A$ and setting a suitable significance level. 

Group A (Bonus group):

- Sample mean: 52 sales calls per week
- Sample standard deviation: 8
- Sample size: n = 35

Group B (No bonus group):

- Sample mean: 48 sales calls per week
- Sample standard deviation: 9
- Sample size: n = 35

b) Calculate the test statistic based on this information. Find the p-value. 

c) What is your conclusion and your recommendation to the company? 

<details>
<summary>Show solutions</summary>

a) $H_0: \mu_A =\mu_B$ vs $H_A: \mu_A>\mu_B$. In this case, the bonus scheme might be expensive, so we want to avoid type I errors (rejecting the null, when it is truly no difference in productivity). We use $\alpha = 1\%$. 

b) $T=1.96$ and p-value $=0.0267$. 

c) The p-value is low, indicating evidence for the alternative hypothesis, but we have set a significance level of 1\%, for which the p-value exceeds. This would lead us to not recommend implementing the bonus, because it does not improve productivity to a high enough degree at this significance level. 

```{python}
m1 = 52; s1 = 8; n1 = 35
m2 = 48; s2 = 9; n2 = 35
stats.ttest_ind_from_stats(m1,s1,n1,m2,s2,n2,alternative="greater")
```

</details>

### Problem 2.3
A university wants to determine if students who attend tutoring sessions perform better on exams than those who do not. Two independent samples of students were taken:

- *Tutoring group*: Mean score = 78, Standard deviation = 10, Sample size = 30
- *Non-tutoring group*: Mean score = 72, Standard deviation = 12, Sample size = 35

a) State the hypotheses.

b) Calculate the test statistic and degrees of freedom.

c) Find the p-value and interpret the result.

<details>
<summary>Show solutions</summary>
a) $H_0: \mu_1 = \mu_2$ vs $H_A: \mu_1 > \mu_2$.

b) 
```{python}
s1 = 10; s2 = 12; n1 = 30; n2 = 35
m1 = 78; m2 = 72;
df = (s1**2/n1 + s2**2/n2)**2 / ((s1**2/n1)**2/(n1-1) + (s2**2/n2)**2/(n2-1))
t = (m1-m2) / ((s1**2/n1 + s2**2/n2)**0.5)
print("df=", df)
print("T=", t)
```

c) The computed p-value is $P(T_{63}>t)=0.0158$. The evidence thus points towards the conclusion that attending tutoring improves performance, due to a low p-value. 

```{python}
print(1-stats.t.cdf(t, df))
```
</details>


## Tests of proportions: One sample
Let $p$ denote a proportion and $p_0$ be the proportion under the null hypothesis. We can then test the null hypothesis $H_0: p=p_0$ against an alternative hypothesis using the test statistic
$$Z = \frac{\hat p-p_0}{\sqrt{p_0(1-p_0)/n}},$$ which is approximately normally distributed when $n$ is sufficiently large and the probabilies are not too small (often $np>5$ is used as a rule of thumb). 

### Problem 3.1
A retail chain is considering phasing out cash payments in favor of digital transactions. Management wants to determine whether at least 60% of customers are already using mobile payment apps (such as Apple Pay or Google Pay) when shopping. If the proportion is significantly higher than 60%, they may move forward with reducing cash payment options.



a) Set up the null hypothesis and alternative hypothesis. Discuss how the test statistic will behave under the various hypotheses.


The retail chain conducts a survey where they ask customers whether they used a mobile payment app for their most recent purchase. Out of the 400 customers asked, 260 used mobile payment apps. 

b) Calculate $Z$ based on this information. What is the p-value? 

c) What does the p-value tell you about people's payment preferences?


<details>
<summary>Show solutions</summary>

a) $H_0: p=0.6$ vs $H_A: \mu>0.6$. The numerator of $Z$ will  be expected close to 0 if the null is zero, making Z close to zero. If $H_A$ is true, $\widehat p$ will be expected larger than 0.6, making Z positive. Large values of $Z$ will favor $H_A$. 

b) $Z = (0.65-0.6)/\sqrt{0.6\cdot 0.4/400}=2.04$ and p-value$=P(Z>2.04)=0.0206$.
```{python}
phat = 260/400
z = (phat-0.6)/np.sqrt(0.6*(1-0.6)/400)
print("Z=", z)
print("Pvalue: ", 1-stats.norm.cdf(z))
```

c) The p-value is low, which indicates evidence against $H_0$. It indicates that the proportion of mobile app payments is above 60\%. 

</details>


### Problem 3.2
A sustainable fashion brand wants to know whether at least 30% of consumers are willing to pay a premium for eco-friendly clothing. If the proportion is significantly higher than 30% with significance level 10\%, they will launch a new premium-priced, eco-friendly clothing line.

They conduct a market survey where respondents indicate whether they would be willing to pay 10% more for sustainably produced clothing.

a) Set up the null- and alternative hypothesis.

The market survey got 500 respondents, and out of those, 166 were willing to pay 10\% more for sustainable clothing. 

b) Calculate $Z$ based on this information. What is the p-value? 

c) What would your recommendation to the fashion brand be?

<details>
<summary>Show solutions</summary>

a) $H_0: p\le 30\%$ vs $H_A: p>30\%$. 

b) $\hat p=166/500= 33.2\%$, $z=(0.332-0.3)/\sqrt{0.3*0.7/500}=1.56$ and
$P(Z>z)=P(Z>1.56)=1-\Phi(1.56)=0.0592$. 

c) At a 10\% signifance level, we would reject the null hypothesis, since the p-value of 0.06 is smaller than 0.1. At this significance level, we would recommend the brand to go ahead with the launch of their eco-friendly clothing. 

```{python}
phat = 166/500
z = (phat-0.3)/np.sqrt(0.3*(1-0.3)/500)
print("Z=", z)
print("Pvalue: ", 1-stats.norm.cdf(z))
```

</details>

### Problem 3.3
A public transportation agency wants to determine whether at least 70% of residents support a new subway line expansion. A survey of 600 residents finds that 435 support the expansion.

a) Formulate the hypotheses.

b) Compute the test statistic and p-value.

c) What is the conclusion?

<details>
<summary>Show solutions</summary>
a) $H_0: p = 0.7$ vs $H_A: p > 0.7$.

b) $$Z=\frac{0.725-0.7}{\sqrt{0.7\cdot 0.3/600}}=1.63$$

p-value $=P(Z>1.63)=0.0907$

```{python}
p_hat = 435/600
z = (p_hat-0.7) / ( (0.7*0.3/600)**0.5 )
print("Z=", z)
print("p-value=", 1-stats.norm.cdf(z))
```

c) A p-value of 9\% indicates that the evidence against the null hypothesis is not very strong, and at a 5\% significance level, we would not reject the null hypothesis. 

</details>


## Tests of proportions: Two samples
Let $p_1$ and $p_2$ denote two proportions. We can then test the null hypothesis $H_0: p_1=p_2$ against an alternative hypothesis using the test statistic
$$Z = \frac{\hat p_1-\hat p_2}{\sqrt{p_\text{pool}(1-p_\text{pool})(1/n_1+1/n_2)}},$$
where $$p_\text{pool}=\frac{n_1\widehat p_1+n_2\widehat p_2}{n_1+n_2}.$$
The test statistic Z is approximately normally distributed. 

### Problem 4.1

An insurance company is testing how the way they frame their sales pitch affects customers' willingness to buy a travel insurance policy. They randomly assign potential customers into two groups:

1. Loss-framed message: "If you don’t buy travel insurance, you could lose thousands in unexpected expenses."
2. Gain-framed message: "If you buy travel insurance, you’ll have peace of mind and financial protection."

Behavioral economics suggests that loss aversion makes people more sensitive to potential losses than gains, meaning the loss-framed message might lead to higher purchase rates. 

a) Set up the null- and alternative hypothesis.  

b) Discuss how the test statistic will behave under the various hypothesis. 

The experiment result in the following data:

- *Loss-framed message*: 200 customers surveyed, 45% purchased insurance
- *Gain-framed message*: 200 customers surveyed, 35% purchased insurance

c) Calculate the test statistic and the p-value.

d) Conclude the test. 


<details>
<summary>Show solutions</summary>
 
Let $p_L$ denote proportion of purchases receiving a loss-framed message and $p_G$ denote proportion of purchases receiving a gain-framed message.
a) $H_0: p_L=p_G$ vs $H_A: p_L>p_G$. 

b) We use $p_1=p_L$ and $p_2 =p_G$ in refence to the formula for the test statistic. If the null hypothesis is true, Z is expected to be close to zero since the numerator is expected to be near 0. If the alternative hypothesis is true, we expect $\hat p_L>\hat p_G$, giving a positive numerator. Thus, large values of Z will favor the alternative hypothesis. 

c) 
```{python}
pL = 0.45
pG = 0.35
nL = 200
nG = 200
pPool = (nL*pL + nG*pG)/(nL+nG)
z = (pL-pG)/np.sqrt(pPool*(1-pPool)*(1/nL+1/nG))
print("Z=",z)
print("pvalue=",1-stats.norm.cdf(z))
```

d) The p-value is low (around 2\%). This indicates that the probability of making a Type I error is low and favor rejecting the null hypothesis. In that sense, the evidence points towards people being willing to pay to avoid loss than they are to potentially gain. 

</details>


### Problem 4.2
An online retailer wants to determine whether offering free shipping increases the proportion of customers who complete their purchases. They run an A/B test, where one group of customers sees free shipping on all orders (Group A), while another group sees the standard shipping fees (Group B). After a week, they compare the proportion of customers who completed a purchase in each group. The retailer asks you to use 5\% significance level. 


a) Formulate the hypothesis problem. 

For the two groups, the retailer gathered the following data: 

Group A (Standard shipping):

- Sample size: 469
- Completed purchases: 191

Group B (Free shipping)

- Sample size: 483
- Completed purchases: 231


b) Perform the test: Find Z and the p-value. 

c) What is your conclusion? 

d) The chief economist in the company has taken a statistics course and learned about the difference between statistical significance and economical significance. How would this distinction influence your recommendation to the company? 

<details>
<summary>Show solutions</summary>

a) $H_0: p_A=p_B$ vs $H_A: p_A<p_B$. 

b) 
```{python}
nA = 469
nB = 483
pA = 191/nA
pB = 231/nB
print(pB-pA)
pPool = (nA*pA + nB*pB)/(nA+nB)
z = (pA-pB)/np.sqrt(pPool*(1-pPool)*(1/nA+1/nB))
print("Z=",z)
print("pvalue=",stats.norm.cdf(z))
```
c) At a 5\% significance level, the free shipping group have a higher completing rate than the standard shipping group. 

d) Here the effect size $|\widehat p_A-\widehat p_B| = 7\%$, that is 7 percentage points higher rate of completing the order if the shipping is free. This increase in completed orders increases the volume, but the free shipping will reduce the margin on each order. We would need more information to assess whether this specific experiment that resulted in a statistically significant increase in volume, also resulted in a economically significant increase of profits. 

</details>

### Problem 4.3
A company is testing whether a new website layout increases the proportion of users who complete a purchase. They conduct an A/B test with the following results:

- *New layout*: 500 users, 210 completed a purchase
- *Old layout*: 500 users, 180 completed a purchase

a) Formulate the hypotheses.

b) Compute the test statistic and p-value.

c) Interpret the result.

<details>
<summary>Show solutions</summary>
a) $H_0: p_1 = p_2$ vs $H_A: p_1 > p_2$. 

b) 
```{python}
from scipy import stats
n1, n2 = 500, 500
p1, p2 = 210/n1, 180/n2
p_pool = (210 + 180) / (n1 + n2)
z = (p1 - p2) / ((p_pool * (1 - p_pool) * (1/n1 + 1/n2)) ** 0.5)
print("Z=", z)
print("p-value=", 1-stats.norm.cdf(z))
```

c) Since the p-value is low, this gives reason to doubt the null hypothesis and indicates that the new layout do increase the proportion of customers placing an order. 

</details>