# The logic of null hypothesis statistical testing

::: {style="padding:56.25% 0 0 0;position:relative;"}
<iframe src="https://player.vimeo.com/video/1165587589?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="The logic of null hypothesis statistical testing">

</iframe>
:::

```{=html}
<script src="https://player.vimeo.com/api/player.js"></script>
```

<br>

Slides for ["The logic of null hypothesis statistical testing"](video-pdf/4/NHSTsteps.pdf)

## Control questions

1.  How do you translate a research question into a testable hypothesis?
2.  How do you translate a hypothesis into null and alternative hypotheses?
3.  What data should be collected to test the hypothesis?
4.  What does a test statistic measure?
5.  What is a null distribution?
6.  How is a p-value computed, and how should it be interpreted?

*… no scientific worker has a fixed level of significance at which from year to year, and in all circumstances, he rejects hypotheses; he rather gives his mind to each particular case in the light of his evidence and his ideas.*

Sir Ronald A. Fisher (1956)

### Recommended reading

-   [Mindless statistics by Gerd Gigerenzer, Journal of Socio-Economics](https://doi.org/10.1016/j.socec.2004.09.033)
