# Datalab 3

The third datalab is about Monte Carlo simulation and bootstrapping the sampling distribution of the maximum likelihood estimator for the exponential distribution. The content of the datalab can be cloned using the following line in git bash:

``` bash
git clone https://github.com/holleland/TECH3_datalab3
```

This will make a local copy of the files on the github repository at the current location of the git bash terminal.

If you dont want to use git bash, you can also open the github [link](https://github.com/holleland/TECH3_datalab2) in your browser and download the files "manually".

The repository consists of three files:

-   **datalab3.ipynb**: The file for you to be working with.
-   **datalab3_sol.ipynb**: Suggestive solutions.
-   **environment.yml**: Conda environment file.

To create the conda environment **TECH3_student** from the environment file, you can open an anaconda prompt and write:

``` bash
conda env create --file environment.yml
```

After the environment has been set up, you can activate the conda environment and open Jupyter Notebbok using

``` bash
conda activate TECH3_student
jupyter notebook
```

For further details on how to set up the conda environment, see the guides on the repository for [TECH2](https://github.com/richardfoltyn/TECH2-H25)

Open the file **datalab3.ipynb**, and go through the document. Write your own code and try to solve the problems yourself before consulting the solutions notebook.
