<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>exercises – TECH3 Applied statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./1-python.html" rel="next">
<link href="./1-gapminder.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/nhh.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">TECH3 Applied statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./calender.html"> 
<span class="menu-text">Calender</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./1-intro.html" aria-current="page"> 
<span class="menu-text">Modules</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./oldexams.html"> 
<span class="menu-text">Old exams</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./reference.html"> 
<span class="menu-text">Reference</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./1-intro.html">Module 1: Summarizing and visualizing data</a></li><li class="breadcrumb-item"><a href="./1-exercises.html">Exercises</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 1: Summarizing and visualizing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-statistical-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Thinking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-working-with-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-summarizing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-summary-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data visualization principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-plotting-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plotting tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-idealised_representations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Idealised representations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-gapminder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gapminder example of good visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-exercises.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Useful python commands</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 2: Probability, random variables, probability distributions and simulations.</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-what-is-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is probability?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-basic-concepts-in-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic concepts in probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-basic-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic probability rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-conditional-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-independent-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Independent events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 3: Estimation, sampling distributions and resampling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 4: Designing studies, hypothesis testing, and quantifying effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-videos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Videos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 5: Measuring relationships and fitting models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-videos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Videos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercises" id="toc-exercises" class="nav-link active" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#module-1" id="toc-module-1" class="nav-link" data-scroll-target="#module-1">Module 1</a>
  <ul class="collapse">
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link" data-scroll-target="#problem-1">Problem 1</a></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a></li>
  <li><a href="#problem-3" id="toc-problem-3" class="nav-link" data-scroll-target="#problem-3">Problem 3</a></li>
  <li><a href="#problem-4" id="toc-problem-4" class="nav-link" data-scroll-target="#problem-4">Problem 4</a></li>
  <li><a href="#problem-5" id="toc-problem-5" class="nav-link" data-scroll-target="#problem-5">Problem 5</a></li>
  <li><a href="#problem-6" id="toc-problem-6" class="nav-link" data-scroll-target="#problem-6">Problem 6</a></li>
  <li><a href="#problem-7" id="toc-problem-7" class="nav-link" data-scroll-target="#problem-7">Problem 7</a></li>
  <li><a href="#problem-8" id="toc-problem-8" class="nav-link" data-scroll-target="#problem-8">Problem 8</a></li>
  <li><a href="#problem-9." id="toc-problem-9." class="nav-link" data-scroll-target="#problem-9.">Problem 9.</a></li>
  <li><a href="#problem-10" id="toc-problem-10" class="nav-link" data-scroll-target="#problem-10">Problem 10</a></li>
  <li><a href="#problem-11" id="toc-problem-11" class="nav-link" data-scroll-target="#problem-11">Problem 11</a></li>
  <li><a href="#problem-12" id="toc-problem-12" class="nav-link" data-scroll-target="#problem-12">Problem 12</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="exercises" class="level1">
<h1>Exercises</h1>
</section>
<section id="module-1" class="level1">
<h1>Module 1</h1>
<section id="problem-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-1">Problem 1</h3>
<p>You are given the following data describing final grades in a tricky statistics course. There were 20 A’s, 97 B’s, 163 C’s, 76 D’s, 31 E’s and 13 F’s.</p>
<ol type="a">
<li><p>What are the most and least common grades?</p></li>
<li><p>Organize this data in a frequency table</p></li>
<li><p>Find the relative frequency of each grade</p></li>
<li><p>What proportion of students failed the course?</p></li>
<li><p>What proportion of students got a B or above?</p></li>
<li><p>What proportion of students got between a C and an E?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p>The most common grade is C with 163 instances, and the least common grade is F with only 13 instances.</p></li>
<li><p>The table can be organised like this for instance:</p></li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Grade</strong></th>
<th><strong>Number</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>20</td>
</tr>
<tr class="even">
<td>B</td>
<td>97</td>
</tr>
<tr class="odd">
<td>C</td>
<td>163</td>
</tr>
<tr class="even">
<td>D</td>
<td>76</td>
</tr>
<tr class="odd">
<td>E</td>
<td>31</td>
</tr>
<tr class="even">
<td>F</td>
<td>13</td>
</tr>
</tbody>
</table>
<ol start="3" type="a">
<li>By summing the amount of respective registered grades we find that there are 400 total. We can now divide the number of instances for each grade by the total of 400 to find the relative frequency. For example, we have 20 instances of A’s out of 400 total grades.</li>
</ol>
<p><span class="math display">\[\frac{20}{400}=0.05\]</span></p>
<p>We can repeat this for all grades and add to the existing table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Grade</strong></th>
<th><strong>Number</strong></th>
<th><strong>Frequency</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>20</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>B</td>
<td>97</td>
<td>0.2425</td>
</tr>
<tr class="odd">
<td>C</td>
<td>163</td>
<td>0.4075</td>
</tr>
<tr class="even">
<td>D</td>
<td>76</td>
<td>0.19</td>
</tr>
<tr class="odd">
<td>E</td>
<td>31</td>
<td>0.0775</td>
</tr>
<tr class="even">
<td>F</td>
<td>13</td>
<td>0.0325</td>
</tr>
</tbody>
</table>
<ol start="4" type="a">
<li><p>The only failing grade is F. We can read from the new table that this we have 0.0325 or 3.25% of students that failed this course.</p></li>
<li><p>To find out what proportion of students got a B or above we need the cumulative frequency. We find this cumulative frequency by summing thge relative frequency of all the relevant cases. In this case “B or above” is the same as achieving a B or an A. The relative frequency of B’s is 0.2425 and for A’s it’s 0.05.</p></li>
</ol>
<p><span class="math display">\[ 0.2425+0.05=0.2925=29.25\%\]</span></p>
<ol start="6" type="a">
<li>To find out what proportion of students got grades between C and E we also need to find the cumulative frequency. Like in e this requires summing the appropriate relative frequencies. From the table in b we can see that the respective relative frequencies are 0.4075 for C, 0.19 for D and 0.0775 for E.</li>
</ol>
<p><span class="math display">\[ 0.4075+0.19+0.0775=0.675=67.5\%\]</span></p>
<p>Alternatively we can take note of the fact that we already know the proportion of students that were below this grade range (the proportion of F’s), as well as the proportion of students that scored above this range (the proportion that scored B or above). By subtracting the proportion of students that scored outside this range from 1 (100%), we should arrive at the same answer.</p>
<p><span class="math display">\[1-0.0325-0.2925=0.675=67.5\%\]</span></p>
</details>
</section>
<section id="problem-2" class="level3">
<h3 class="anchored" data-anchor-id="problem-2">Problem 2</h3>
<p>You hear that the average starting salary after finishing a master’s degree at NHH is NOK 550 000, the median salary is NOK 525 000, and the mode is NOK 500 000. What can you infer from this?</p>
<details>
<summary>
Show solutions
</summary>
<p>Though they might seem similar on a surface level, the mode, median and mean give slightly different information.</p>
<p>The mode tells us what the most common observation in the data is. In our case this means that the <strong>most common</strong> starting salary after graduating with a master’s degree from NHH is NOK 500 000.</p>
<p>The median is the “middle value” in the dataset, meaning that 50 percent of the observations should be below this value, whilst the other 50 percent should be above this value. In our case it means that half of graduates will have a starting salary that’s NOK 525 000 or below whilst the other half get a starting salary of NOK 525 000 or above.</p>
<p>Finally, the mean reflects the <strong>average</strong> of the dataset. We can tell here that the average is NOK 550 000. Additionally, by looking at everything in context we can also make some minor inferences. We see that the mean is higher than the median, indicating that some datapoints are skewing the average upwards, i.e.&nbsp;some graduates are earning really well compared to their peers from the get go. Additionally we see that the mode is 500 000, compared to the mean of 550 000. As the mode is the most common observation and is below the median, this seems to suggest that those who end up with a higher starting salary start with a substantially higher one compared to their peers, for the average to skew above the median.</p>
</details>
</section>
<section id="problem-3" class="level3">
<h3 class="anchored" data-anchor-id="problem-3">Problem 3</h3>
<p>At a retail chain Floormart the Median pay by hour is $25, but the average is $33 per hour. What does this suggest?</p>
<details>
<summary>
Show solutions
</summary>
<p>Similar to in Problem 2, the indication here seems to be that some employees may be earning significantly more than others. Exactly how many employees are earning more and by how much is impossible to tell given our available information, but it seems likely that the executives or managers and above may have significantly higher pay than most employees in Floormart. These few employees having a much higher pay than for instance new hires or other low level workers could explain this disparity.</p>
</details>
</section>
<section id="problem-4" class="level3">
<h3 class="anchored" data-anchor-id="problem-4">Problem 4</h3>
<p>If possible, find the mode, median and mean of the following set of dice rolls</p>
<p><span class="math display">\[4,6,5,5,6,2,1,6,3,6,2,1,3\]</span></p>
<details>
<summary>
Show solutions
</summary>
<p>The mode is the most common observation. As 6 appears 4 times here, more than any other roll, 6 is the mode.</p>
<p>To clearly find the median we can sort the data from lowest to highest observation. We then end up with {1,1,2,2,3,3,4,5,5,6,6,6,6}. We have 13 observations here, so the median will be given by the 7th observation from the bottom. In our case we find that 4 is the median.</p>
<p>Finally we can find the mean by taking the average of the observed rolls.</p>
<p>Recall the formula for averages is</p>
<p><span class="math display">\[\overline{X}=\frac{1}{n}\sum_{i=1}^{n}X_i\]</span></p>
<p>In our case we can just sum each obvservation and divide by the number of observations, which is 13.</p>
<p><span class="math display">\[\begin{align*}
\overline{X}&amp;=\frac{1}{13}(1+1+2+2+3+3+4+5+5+6+6+6+6)\\
&amp;=\frac{50}{13}\approx3.846
\end{align*}\]</span></p>
</details>
</section>
<section id="problem-5" class="level3">
<h3 class="anchored" data-anchor-id="problem-5">Problem 5</h3>
<p>If possible, find the mode, median and mean of the following set of favorite colors</p>
<p>red,blue,blue,green,yellow,green,green,blue,red,red,pink,purple,blue</p>
<details>
<summary>
Show solutions
</summary>
<p>The mode is found by finding the most common observation. Here “blue” is the most common favourite color, with 4 instances, and thus “blue” is our mode.</p>
<p>It is not possible to find a median within this data, as we need to be able to logically sort the data to be able to have a meaningful median. I.e. as the data is not ordinal, we can’t find a median.</p>
<p>It is not possible to find a mean from this data. We need numerical data to be able to give a meaningful mean.</p>
</details>
</section>
<section id="problem-6" class="level3">
<h3 class="anchored" data-anchor-id="problem-6">Problem 6</h3>
<p>What level of data is required to find modes, means, and medians? (Categorical, ordinal, etc.)</p>
<details>
<summary>
Show solutions
</summary>
<p>To find a mode we need at least categorical data.</p>
<p>To find a median we need data that is ordinal.</p>
<p>To find a mean we need data that is numerical.</p>
</details>
</section>
<section id="problem-7" class="level3">
<h3 class="anchored" data-anchor-id="problem-7">Problem 7</h3>
<p>You get the dataset <span class="math display">\[1,1,1,1,1,3,3,3,3,7,7,7,7,9,9,9.\]</span></p>
<ol type="a">
<li><p>Find the mode, median and mean of the above set.</p></li>
<li><p>Find the the first and third quartile of the set.</p></li>
<li><p>What are the 0th and 100th percentiles of the set?</p></li>
<li><p>Would the median change if you were to add a single datapoint of 11 to the set? What would the median of the new set be? What if we were to add two datapoints of 11?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li>The most common observation is 1, thus the mode is 1. We have an even number of observations in this set, 16.</li>
</ol>
<p>By taking the average of the two middlemost values we will find the median. Both the 8th and 9th value in the set are 3, and thus the median of the set is 3.</p>
<p>We can find the mean by taking the average of the data.</p>
<p><span class="math display">\[\begin{align*}
\overline{X}&amp;=\frac{1}{16}(1+1+1+1+1+3+3+3+3+7+7+7+7+9+9+9)\\
&amp;=\frac{72}{16}=4.5
\end{align*}\]</span></p>
<ol start="2" type="a">
<li>The first quartile indicates that 25% of observations should be below this threshold. In our case we see that the first quartile would fall between the 4th and 5th observation, which are both 1, telling us the 1st qaurtile is 1.</li>
</ol>
<p>The 3rd quartile indicates that 75% of observations should be below it. The 12th and 13th observations are both 7, letting us know that the third quartile is 7.</p>
<ol start="3" type="a">
<li><p>The 0th percentile indicates the minimum value of the set while the 100th percentile indicates the maximium value. We can then say that the 0th percentile is 1 and the 100th percentile is 9.</p></li>
<li><p>If we add a datapoint of 11 to the set, we would now have 17 observations, meaning that the 9th observation from the bottom would indicate the median. The 9th observation from the bottom is 3, which is the same median as in the previous case, so the median would not change. If we were to add two datapoints of 11 to the set, we would have 18 observations. With 18 observations we have to take the average of the two middlemost observations after sorting. The two middlemost observations are the 9th and 10th ones from the bottom, meaning 3 and 7. The average would then be:</p></li>
</ol>
<p><span class="math display">\[\frac{1}{2}(3+7)=\frac{10}{2}=5\]</span></p>
<p>The median in this case would be 5, so it would indeed change from the previous case.</p>
</details>
</section>
<section id="problem-8" class="level3">
<h3 class="anchored" data-anchor-id="problem-8">Problem 8</h3>
<p>You get this dataset of a group of 11 people and their respective heights in centimetres.</p>
<p><span class="math display">\[184,157,168,172,198,154,192,161,186,177,165.\]</span></p>
<ol type="a">
<li><p>Find the mean/average height of this group.</p></li>
<li><p>Find the variance in height in this group and the standard deviation.</p></li>
<li><p>Does the variance and standard deviation seem big, small or somewhere in between in this context?</p></li>
<li><p>What would be the effect on the variance of adding another person to the sample that is of the average height we found in a. Would the variance increase, decrease or stay the same?</p></li>
<li><p>What would be the effect of adding another person to the group that’s 200cm tall. Would the variance increase, decrease or stay the same? Why is the change intuitive?</p></li>
<li><p>What would be the effect of adding another person to the group that’s 140cm tall. Would the variance increase, decrease or stay the same? Why is the change intuitive? Why is the change in variance here greater than the one in e.?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<p>a)We sum our observations, and divide by 11, which is the number of observations.<br>
</p>
<p><span class="math display">\[\begin{align*}
\overline{X}=\frac{1}{11}(&amp;184+157+168+172+198+154+192+161 \\ &amp;+186+177+165)=\frac{1914}{11}=174
\end{align*}\]</span></p>
<ol start="2" type="a">
<li>Here we need to first recall the formula for variance.</li>
</ol>
<p><span class="math display">\[S_X^2=\frac{1}{n-1}\sum_{i=1}^{n}(X_i-\overline{X})^2\]</span></p>
<p>We recall that the mean we found in a is 174 and that we have 11 total observations. Now we have everything we need to plug in our data and find the variance.</p>
<p><span class="math display">\[\begin{align*}
S_X^2&amp;=\frac{1}{11-1}\bigg((184-174)^2+(157-174)^2+(168-174)^2 \\ &amp;+(172-174)^2+(198-174)^2+(154-174)^2+(192-174)^2+(161-174)^2+ \\&amp;(186-174)^2+(177-174)^2+(165-174)^2\bigg)=\frac{2132}{10}=213.2
\end{align*}\]</span></p>
<p>Now we only need to find standard deviation.Recall that the standard deviation is the square root of the variance.</p>
<p><span class="math display">\[S_X=\sqrt{S_X^2}=\sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(X_i-\overline{X})^2}\]</span></p>
<p>In our case we need only plug in the variance we have already found.</p>
<p><span class="math display">\[S_X=\sqrt{213.2}\approx14.6\]</span></p>
<ol start="3" type="a">
<li><p>Variance is hard to interpret directly, but the standard deviation is very simple. The standard deviation tells us that the average absolute difference from the mean in our data. Here we see that the standard deviation is 14.6cm, so on average the people in this group are 14.6 away from the the mean in terms of height. This means the we would expect a random person from this group to be either about 159cm tall or 188cm tall. It’s not all that simple to say if this is a lot or not, that depends on the data collected. If this is a sample from a group of Norwegian men age 20, this could seem like a very big standard deviation and variance. However, if this is a group of men and women with an age range from 14 to 35, this might not seem like such a big variance.</p></li>
<li><p>If we were to only add more people of the average height we found (174cm) the variance would decrease. There are two effects in play here. The when we add more observations our n gets bigger, and thus we divide by a larger number, but we also have to add another squared difference from the mean. In this case we add another observation that’s exactly equal to the mean. Firstly what effect will this have on the mean itself? Intuitively, the mean will <strong>not</strong> change in this case. Notice that the squared difference between the mean and itself is 0.</p></li>
</ol>
<p><span class="math display">\[(\overline{X}-\overline{X})^2=(174-174)^2=0^2=0\]</span></p>
<p>Let’s now add this to our equation for variance. Since we have one more observation we will be dividing by (n-1)+1=n, instead of n-1.</p>
<p><span class="math display">\[\begin{align*}
S_{X1}^2&amp;=\frac{1}{n} \left(\sum_{i=1}^n(X_i-\overline{X})^2+(\overline{X}-\overline{X})^2\right)
    =\frac{1}{n} \left(\sum_{i=1}^n(X_i-\overline{X})^2+0\right)
    \\&amp;=\frac{1}{n} \left(\sum_{i=1}^n(X_i-\overline{X})^2\right)
    &lt;\frac{1}{n-1} \left(\sum_{i=1}^n(X_i-\overline{X})^2\right)=S_X^2
\end{align*}\]</span></p>
<p><strong>For those that don’t find it intuitive that the mean stays the same when you add more observations the equal the mean:</strong></p>
<p>Underneath I have shown algebraically what happens to the mean when you add <strong>one</strong> more observation in the sample that equals the mean. This can easily be extended to adding any number, <strong>m</strong>, more observations (try for yourself!).</p>
<p><span class="math display">\[\begin{align*}
\overline{X}_1&amp;=\frac{1}{n+1} \left( \sum_{i=1}^{n}X_i+\overline{X} \right)=\frac{1}{n+1}\left( \frac{n}{n}\sum_{i=1}^nX_i+\overline{X} \right) \\ &amp;=\frac{1}{n+1}\left(n\overline{X}+\overline{X}\right) = \frac{n+1}{n+1}\overline{X}=\overline{X}
\end{align*}\]</span></p>
<p>Now, let’s see what happens to the variance, when we add another observation that equals the mean.</p>
<p><span class="math display">\[S_{X1}^2= \frac{1}{n-1+1}\left(\sum_{i=1}^n(X_i-\overline{X})^2+(\overline{X}-\overline{X})^2\right)\]</span></p>
<ol start="5" type="a">
<li>We can amend our data by adding the new observation of 200cm, and with this we can compute the new mean and variance. We will notice that since we add an observation that is higher than the average, the mean will increase, and we will also find that the variance (and consequently the standard deviation) will both increase. The new values will be:</li>
</ol>
<p><span class="math display">\[ \overline{X}\approx176.17 \\ S_X^2\approx250.15\]</span></p>
<p>The intuition is simply that since our new observation is very different from our mean, the variance will increase. Adding the new squared difference has a greater effect than dividing by a higher number. Recall that our original mean was 174 and our original standard deviation was approximately 14.6. This means that the average absolute difference between an observation and the mean is about 14.6.</p>
<p><span class="math display">\[|200-174|=26&gt;14.6\]</span></p>
<p>This means that by adding this new observation, since it’s difference from the mean is so clearly much greater than the standard deviation, the standard deviation should increase by adding this observation. When the standard deviation increases, so will the variance. (Note that we can only intuit in this way when the absolute difference between the new observation and the mean is quite a bit greater than the standard deviation. The intuition you should build from this is that new observations that are <strong>very different</strong> from the mean will <strong>increase</strong> the variance, and consequently, observations that are <strong>close</strong> to the mean will <strong>decrease</strong> the variance.)</p>
<ol start="6" type="a">
<li>This case is very similar to the one in e. The only notable difference is that we add an observation that is much <strong>lower</strong> than the mean, rather than one which is much <strong>higher</strong>. Computing the the new mean and variance we get:</li>
</ol>
<p><span class="math display">\[\overline{X}\approx171.17 \\ S_X^2\approx290.15 \]</span></p>
<p>The intuition here is exactly the same as in e. Since the new observation is very different from the mean, the variance should increase. Let’s compare the absolute difference between the mean and the new observation to the standard deviation.</p>
<p><span class="math display">\[|140-174|=|-34|=34&gt;14.6\]</span></p>
<p>From this it should also be clear why the change in variance here is greater than the one in e. Since 140 is an observation that is <strong>farther away</strong> from the mean (174), than 200, the increase in variance will be greater.</p>
<p>(<strong>Extra challenge for those that can’t get enough</strong>: Can you intuit what would happen in an opposite case? Would the variance change more if we added if we added a new observation of someone that was 177cm tall or with someone that was 172cm tall?)</p>
</details>
</section>
<section id="problem-9." class="level3">
<h3 class="anchored" data-anchor-id="problem-9.">Problem 9.</h3>
<p>Recall the variance and standard deviation found in Problem 8b. Imagine that instead of the height of people, the variance and standard deviation was instead found from data on height of trees (Note: the collected data is not necessarily the same even though the variance is the same). Does the variance and standard deviation feel big, small or somewhere in between in this context?</p>
<details>
<summary>
Show solutions
</summary>
<p>This problem is mainly about interpretation, but let’s consider the standard deviation. We have a standard deviation of 14.6cm. A height difference of 14.6cm between two <strong>people</strong> is quite large, and very noticeable. When it comes to trees, however, that is not necessarily the case. Short trees can be as short as just a few centimeters, where as the tallest trees can reach upwards of 100 meters(!). Even without considering the shortest and tallest trees, we find that there can easily be several meters of difference between completely ordinary trees. Since we only know that we are working with trees in this case, it’s hard to assume anything about the data, but looking at the standard deviation we can tell that these trees must be <strong>very similar</strong> in stature as far as trees are considered. If anything, this variance, that seems quite reasonable (or even very large), when we consider the heights of people, seems completely minuscule when we consider trees instead. It’s impossible to say whether variance and standard deviation is large or small with no context, as is illustrated with this comparison.</p>
</details>
</section>
<section id="problem-10" class="level3">
<h3 class="anchored" data-anchor-id="problem-10">Problem 10</h3>
<p>In what scenario would we get a Variance of 0?</p>
<details>
<summary>
Show solutions
</summary>
<p>For the variance to be 0, our observations simply can’t vary. This means that all observations have to have the same value.</p>
<p>This can be shown algebraically. Let all observations <span class="math inline">\(X_i=X\)</span> be equal. Then <span class="math display">\[\overline{X}=\frac{1}{n}\sum_{i=1}^nX_i=\frac{1}{n}\sum_{i=1}^nX=\frac{n}{n}X=X \]</span></p>
<p>It’s clear that all observations here are equal to the mean, which gives us.</p>
<p><span class="math display">\[\begin{align*}
S_X^2&amp;=\frac{1}{n-1}\sum_{i=1}^n(X_i-\overline{X})^2=\frac{1}{n-1}\sum_{i=1}^n(\overline{X}-\overline{X})^2 \\ &amp;=\frac{1}{n-1}\sum_{i=1}^n0=\frac{0}{n-1}=0
\end{align*}\]</span></p>
<p>By looking at the equation for the variance, we can tell that if <strong>any</strong> one or more observations were to deviate from the mean, there would be variance in our data.</p>
</details>
</section>
<section id="problem-11" class="level3">
<h3 class="anchored" data-anchor-id="problem-11">Problem 11</h3>
<p>You have a dataset with six observations and a mean of 50. Show that when you have any observations outside of the interval [45;55] the variance will always be greater than 5.</p>
<details>
<summary>
Show solutions
</summary>
<p>We have received this information:</p>
<p><span class="math display">\[n=6, \ \overline{X}=50\]</span></p>
<p>To show that that our variance will always be greater than 5 when we have an observation <strong>outside</strong> of the given interval, let’s consider the situation that would create the <strong>least</strong> variance. Consider a situation where only <strong>one</strong> observation is 55, and the rest of the observations have to make up for this by all of them being a bit less than 50. Since we use squared sums when we compute the variance, we would get the least variance from the 5 last observations being equally close to to the mean. We can use an equation to find out what each of these 5 observations have to equal. For this we use the formula to calculate an average.</p>
<p><span class="math display">\[\overline{X}=\frac{1}{n}\sum_{i=1}^nX_i\]</span></p>
<p>Since we know that the average we’re looking for is 50, <strong>one</strong> observation is 55 and the last 5 observations are equal, we get an equation with one variable.</p>
<p><span class="math display">\[\begin{align*}
50&amp;=\frac{1}{6}(5X+55) \\
\Rightarrow 6\cdot 50&amp;=5X+55 \\
\Rightarrow 300&amp;=5X+55 \\
\Rightarrow 300-55&amp;=5X \\
\Rightarrow 245&amp;=5X \\
\Rightarrow X&amp;=49
\end{align*}\]</span></p>
<p>Now we have a clear view of the data that would give the minimum variance. {49,49,49,49,49,55} Finally, we can compute the variance.</p>
<p><span class="math display">\[\begin{align*}
S_X^2&amp;=\frac{1}{6-1}\left(5(49-50)^2+(55-50)^2 \right) \\
&amp;=\frac{1}{5}(5\cdot(-1)^2+5^2)=\frac{1}{5}(5+25) \\
&amp;=\frac{30}{5}=6&gt;5
\end{align*}\]</span></p>
</details>
</section>
<section id="problem-12" class="level3">
<h3 class="anchored" data-anchor-id="problem-12">Problem 12</h3>
<p>You are given the following dataset containing information about survival of people travelling on the Titanic in 1912. The data contains counts of how many who survived or not of groups by ticket class, sex, age (child/adult). Can you categorize the columns based on whether they are categorical, numeric, binary, integer or real?</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Class</th>
<th style="text-align: left;">Sex</th>
<th style="text-align: left;">Age</th>
<th style="text-align: left;">Survived</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1st</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2nd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crew</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1st</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">2nd</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crew</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Child</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1st</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Adult</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">118</td>
</tr>
<tr class="even">
<td style="text-align: left;">2nd</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Adult</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">154</td>
</tr>
</tbody>
</table>
</div>
</div>
<details>
<summary>
Show suggested solutions
</summary>
<ul>
<li>Class: Categorical, although could be treated as ordinal (1st &gt; 2nd &gt; 3rd &gt; Crew)</li>
<li>Sex: Binary (Male/female)</li>
<li>Age: Binary (Child/adult)</li>
<li>Survived: Binary (no/yes)</li>
<li>Freq: Numerical, integer.</li>
</ul>
</details>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./1-gapminder.html" class="pagination-link" aria-label="Gapminder example of good visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Gapminder example of good visualization</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./1-python.html" class="pagination-link" aria-label="Useful python commands">
        <span class="nav-page-text">Useful python commands</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>