<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>exercises – TECH3 Applied statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./5-intro.html" rel="next">
<link href="./4-python.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-37d81edd14c5e89b87cd66af6a72e2e5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/nhh.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">TECH3 Applied statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./calender.html"> 
<span class="menu-text">Calender</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./1-intro.html" aria-current="page"> 
<span class="menu-text">Modules</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./seminar1.html"> 
<span class="menu-text">Seminars</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./datalabs.html"> 
<span class="menu-text">Datalabs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./oldexams.html"> 
<span class="menu-text">Old exams</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./4-intro.html">Module 4: Designing studies, hypothesis testing, and quantifying effects</a></li><li class="breadcrumb-item"><a href="./4-exercises.html">Exercises</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 1: Summarizing and visualizing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-statistical-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical Thinking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-working-with-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-summarizing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarizing data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-summary-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data visualization principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-plotting-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plotting tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-idealised_representations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Idealised representations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-gapminder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gapminder example of good visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 2: Probability, random variables, probability distributions and simulations.</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-what-is-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is probability?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-basic-concepts-in-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic concepts in probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-basic-probability-rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic probability rules</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-conditional-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-independent-events.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Independent events</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-bayes-rule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayes rule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-discrete-random-variables-and-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Discrete random variables and distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-exp-var-discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Expectation and variance of discrete random variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 3: Estimation, sampling distributions and resampling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-population-vs-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Population vs sample</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-what-is-a-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is a model?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-sampling-error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sampling error and distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-central-limit-theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Central Limit Theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-what-is-an-estimator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is an estimator?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-maximum-likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Maximum likelihood</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-random-number-generation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random number generation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-monte-carlo-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Monte Carlo simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 4: Designing studies, hypothesis testing, and quantifying effects</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-hypothesis-testing-in-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing in Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-power-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Power analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-videos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Videos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-exercises.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Module 5: Measuring relationships and fitting models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-textbook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Textbook</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-categorical-relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling categorical relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-contingency-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contingency tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-simpsons-paradox.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simpson’s paradox</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-continuous-relationships-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling continuous relationships: Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-correlation-and-causation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation and causation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-assessing-the-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assessing the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-prediction-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prediction models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercises" id="toc-exercises" class="nav-link active" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test">One-sample t-test</a>
  <ul class="collapse">
  <li><a href="#problem-1.1" id="toc-problem-1.1" class="nav-link" data-scroll-target="#problem-1.1">Problem 1.1</a></li>
  <li><a href="#problem-1.2" id="toc-problem-1.2" class="nav-link" data-scroll-target="#problem-1.2">Problem 1.2</a></li>
  <li><a href="#problem-1.3" id="toc-problem-1.3" class="nav-link" data-scroll-target="#problem-1.3">Problem 1.3</a></li>
  <li><a href="#problem-1.4" id="toc-problem-1.4" class="nav-link" data-scroll-target="#problem-1.4">Problem 1.4</a></li>
  <li><a href="#problem-1.5" id="toc-problem-1.5" class="nav-link" data-scroll-target="#problem-1.5">Problem 1.5</a></li>
  <li><a href="#problem-1.6" id="toc-problem-1.6" class="nav-link" data-scroll-target="#problem-1.6">Problem 1.6</a></li>
  </ul></li>
  <li><a href="#two-sample-t-test" id="toc-two-sample-t-test" class="nav-link" data-scroll-target="#two-sample-t-test">Two-sample t-test</a>
  <ul class="collapse">
  <li><a href="#problem-2.1" id="toc-problem-2.1" class="nav-link" data-scroll-target="#problem-2.1">Problem 2.1</a></li>
  <li><a href="#problem-2.2" id="toc-problem-2.2" class="nav-link" data-scroll-target="#problem-2.2">Problem 2.2</a></li>
  <li><a href="#problem-2.3" id="toc-problem-2.3" class="nav-link" data-scroll-target="#problem-2.3">Problem 2.3</a></li>
  <li><a href="#problem-2.4" id="toc-problem-2.4" class="nav-link" data-scroll-target="#problem-2.4">Problem 2.4</a></li>
  <li><a href="#problem-2.5" id="toc-problem-2.5" class="nav-link" data-scroll-target="#problem-2.5">Problem 2.5</a></li>
  <li><a href="#problem-2.6" id="toc-problem-2.6" class="nav-link" data-scroll-target="#problem-2.6">Problem 2.6</a></li>
  <li><a href="#problem-2.7" id="toc-problem-2.7" class="nav-link" data-scroll-target="#problem-2.7">Problem 2.7</a></li>
  </ul></li>
  <li><a href="#tests-of-proportions-one-sample" id="toc-tests-of-proportions-one-sample" class="nav-link" data-scroll-target="#tests-of-proportions-one-sample">Tests of proportions: One sample</a>
  <ul class="collapse">
  <li><a href="#problem-3.1" id="toc-problem-3.1" class="nav-link" data-scroll-target="#problem-3.1">Problem 3.1</a></li>
  <li><a href="#problem-3.2" id="toc-problem-3.2" class="nav-link" data-scroll-target="#problem-3.2">Problem 3.2</a></li>
  <li><a href="#problem-3.3" id="toc-problem-3.3" class="nav-link" data-scroll-target="#problem-3.3">Problem 3.3</a></li>
  <li><a href="#problem-3.4" id="toc-problem-3.4" class="nav-link" data-scroll-target="#problem-3.4">Problem 3.4</a></li>
  </ul></li>
  <li><a href="#tests-of-proportions-two-samples" id="toc-tests-of-proportions-two-samples" class="nav-link" data-scroll-target="#tests-of-proportions-two-samples">Tests of proportions: Two samples</a>
  <ul class="collapse">
  <li><a href="#problem-4.1" id="toc-problem-4.1" class="nav-link" data-scroll-target="#problem-4.1">Problem 4.1</a></li>
  <li><a href="#problem-4.2" id="toc-problem-4.2" class="nav-link" data-scroll-target="#problem-4.2">Problem 4.2</a></li>
  <li><a href="#problem-4.3" id="toc-problem-4.3" class="nav-link" data-scroll-target="#problem-4.3">Problem 4.3</a></li>
  <li><a href="#problem-4.4" id="toc-problem-4.4" class="nav-link" data-scroll-target="#problem-4.4">Problem 4.4</a></li>
  </ul></li>
  <li><a href="#normal-distribution-and-student-t-dsitribution" id="toc-normal-distribution-and-student-t-dsitribution" class="nav-link" data-scroll-target="#normal-distribution-and-student-t-dsitribution">Normal distribution and student t dsitribution</a>
  <ul class="collapse">
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link" data-scroll-target="#problem-1">Problem 1</a></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a></li>
  <li><a href="#problem-3" id="toc-problem-3" class="nav-link" data-scroll-target="#problem-3">Problem 3</a></li>
  <li><a href="#problem-4" id="toc-problem-4" class="nav-link" data-scroll-target="#problem-4">Problem 4</a></li>
  <li><a href="#problem-5" id="toc-problem-5" class="nav-link" data-scroll-target="#problem-5">Problem 5</a></li>
  <li><a href="#problem-6" id="toc-problem-6" class="nav-link" data-scroll-target="#problem-6">Problem 6</a></li>
  <li><a href="#problem-7" id="toc-problem-7" class="nav-link" data-scroll-target="#problem-7">Problem 7</a></li>
  <li><a href="#problem-8" id="toc-problem-8" class="nav-link" data-scroll-target="#problem-8">Problem 8</a></li>
  <li><a href="#problem-9" id="toc-problem-9" class="nav-link" data-scroll-target="#problem-9">Problem 9</a></li>
  <li><a href="#problem-10" id="toc-problem-10" class="nav-link" data-scroll-target="#problem-10">Problem 10</a></li>
  <li><a href="#problem-11" id="toc-problem-11" class="nav-link" data-scroll-target="#problem-11">Problem 11</a></li>
  <li><a href="#problem-12" id="toc-problem-12" class="nav-link" data-scroll-target="#problem-12">Problem 12</a></li>
  <li><a href="#problem-13" id="toc-problem-13" class="nav-link" data-scroll-target="#problem-13">Problem 13</a></li>
  <li><a href="#problem-14" id="toc-problem-14" class="nav-link" data-scroll-target="#problem-14">Problem 14</a></li>
  <li><a href="#problem-15" id="toc-problem-15" class="nav-link" data-scroll-target="#problem-15">Problem 15</a></li>
  <li><a href="#problem-16" id="toc-problem-16" class="nav-link" data-scroll-target="#problem-16">Problem 16</a></li>
  <li><a href="#problem-17" id="toc-problem-17" class="nav-link" data-scroll-target="#problem-17">Problem 17</a></li>
  <li><a href="#problem-18" id="toc-problem-18" class="nav-link" data-scroll-target="#problem-18">Problem 18</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./4-intro.html">Module 4: Designing studies, hypothesis testing, and quantifying effects</a></li><li class="breadcrumb-item"><a href="./4-exercises.html">Exercises</a></li></ol></nav></header>




<section id="exercises" class="level1">
<h1>Exercises</h1>
<section id="one-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-t-test">One-sample t-test</h2>
<p>For the following exercises, we will use the test statistic for one-sample t-test with null hypothesis <span class="math inline">\(H_0:\mu=\mu_0\)</span>: <span class="math display">\[T=\frac{\bar x-\mu_0}{s/\sqrt{n}},\]</span> where <span class="math inline">\(n\)</span> is the sample size, <span class="math inline">\(\bar x\)</span> is the sample mean, <span class="math inline">\(s\)</span> is the sample standard deviation and <span class="math inline">\(\mu_0\)</span> is the expected value under the null hypothesis.</p>
<section id="problem-1.1" class="level3">
<h3 class="anchored" data-anchor-id="problem-1.1">Problem 1.1</h3>
<p>A company selling premium coffee beans wants to determine whether reducing the price of its product leads to a significant increase in the average number of bags sold per day. The marketing team conducted a test by lowering the price for a month in select stores and measuring the sales volume. They want to analyze whether the mean daily sales after the price reduction are significantly higher than before.</p>
<ol type="a">
<li>Set up the null- and alternative hypothesis, and decide on a suitable significance level.</li>
</ol>
<p>Before the price reduction, the mean daily sales were 200 bags. After the price reduction, a sample of 30 days of sales data showed a sample mean of 215 bags, with standard deviation 25 bags.</p>
<ol start="2" type="a">
<li><p>Calculate the test statistic.</p></li>
<li><p>Find the p-value. What is the conclusion?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu\le 200\)</span> vs <span class="math inline">\(H_1: \mu&gt;200\)</span>. We could allow for a relatively high significance level in this context, because rejecting a true null hypothesis (Type I error) will most likely not have large consequences, e.g.&nbsp;<span class="math inline">\(\alpha =0.1\)</span>.</p></li>
<li><p><span class="math inline">\(T=(215-200)/(25/\sqrt{30})=3.29\)</span></p></li>
<li><p><span class="math inline">\(\text{p-value}=P(T_{29}&gt;3.29)=0.00132\)</span>. The p-value is very low, indicating that we may reject the null hypothesis at (almost) any significance level in (a). The company should continue with the reduced price.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.t.cdf(<span class="fl">3.29</span>, <span class="dv">29</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.0013169979736814552</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-1.2" class="level3">
<h3 class="anchored" data-anchor-id="problem-1.2">Problem 1.2</h3>
<p>A large company is trying to encourage employees to save more for retirement. Previously, employees had to actively sign up for the company’s pension savings plan (opt-in system). Recently, the company changed its policy so that employees are automatically enrolled in the plan but can opt out if they wish (opt-out system). Behavioral economists suggest that default options strongly influence decision-making, leading to higher participation rates in savings plans.</p>
<p>The HR department wants to test with a significance level of 5% whether the average monthly contribution to the retirement plan has increased significantly after implementing the opt-out system.</p>
<ol type="a">
<li>Set up the null- and alternative hypothesis.</li>
</ol>
<p>Before the change, the average monthly contribution was $250 per employee. After the policy change, a random sample of 50 employees showed: Sample mean of $270 and standard deviation of $90.</p>
<ol start="2" type="a">
<li><p>Calculate the test statistic.</p></li>
<li><p>Find the p-value. What is the conclusion?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu\le 250\)</span> vs <span class="math inline">\(H_1: \mu&gt;250\)</span>.</p></li>
<li><p><span class="math inline">\(T=(270-250)/(90/\sqrt{50})=1.57\)</span></p></li>
<li><p><span class="math inline">\(\text{p-value}=P(T_{29}&gt;3.29)=0.0613\)</span>. The p-value is higher than 5%, indicating that we may reject not the null hypothesis. The pension payments have not increased due to the change from opting in to opting out.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.t.cdf(<span class="fl">2.94</span>, <span class="dv">49</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.002498152330066006</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-1.3" class="level3">
<h3 class="anchored" data-anchor-id="problem-1.3">Problem 1.3</h3>
<p>A nutritionist wants to test whether a new diet plan leads to a significant reduction in average daily calorie intake. A sample of 40 individuals followed the diet for one month, and their average daily calorie intake was recorded.</p>
<p>The recommended daily intake before the diet was 2200 kcal. After one month, the sample had a mean intake of 2100 kcal with a standard deviation of 250 kcal.</p>
<ol type="a">
<li><p>Set up the null- and alternative hypotheses.</p></li>
<li><p>Calculate the test statistic.</p></li>
<li><p>Find the p-value and interpret the result.</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu\geq 2200\)</span> vs <span class="math inline">\(H_1: \mu&lt;2200\)</span>.</p></li>
<li><p><span class="math display">\[T=\frac{2100-2200}{250/\sqrt{40}}=-2.53\]</span></p></li>
<li><p><span class="math display">\[\text{p-value}=P(T_{39}&lt;-2.53)=0.0079\]</span></p></li>
</ol>
<p>Since the p-value is lower than the conventional 5% significance level, we reject the null hypothesis, suggesting that the new diet plan significantly reduces daily calorie intake.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.t.cdf(<span class="op">-</span><span class="fl">2.53</span>, <span class="dv">39</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.007778305846562239</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-1.4" class="level3">
<h3 class="anchored" data-anchor-id="problem-1.4">Problem 1.4</h3>
<p>A smartphone manufacturer wants to determine whether the battery life of their new model is significantly different from the advertised 24 hours. A sample of 50 devices was tested, showing a mean battery life of 23.5 hours with a standard deviation of 1.2 hours.</p>
<ol type="a">
<li><p>Formulate the hypotheses.</p></li>
<li><p>Compute the test statistic.</p></li>
<li><p>Determine the p-value and state your conclusion.</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu=24\)</span> vs <span class="math inline">\(H_1: \mu\neq 24\)</span>.</p></li>
<li><p><span class="math display">\[T=\frac{23.5-24}{1.2/\sqrt{50}}=-2.946\]</span></p></li>
<li><p><span class="math display">\[\text{p-value}=2 \times P(T_{49}&lt;-2.94)=0.0049\]</span></p></li>
</ol>
<p>Since the p-value is very small, we reject the null hypothesis, indicating that the battery life is significantly different from 24 hours.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">2</span><span class="op">*</span>stats.t.cdf(<span class="op">-</span><span class="fl">2.946</span>, <span class="dv">49</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.004914894166068594</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-1.5" class="level3">
<h3 class="anchored" data-anchor-id="problem-1.5">Problem 1.5</h3>
<p>A fitness instructor claims that the average resting pulse rate of adults in their program is less than 70 beats per minute. A sample of 10 participants yields:</p>
<p><span class="math display">\[ \text{Pulse Rates:} \ 68, \ 72, \ 69,  \ 71,  \ 67,  \ 65,  \ 70,\ 66,\  68, \ 64 \]</span></p>
<p>Assume approximate normality.</p>
<ol type="a">
<li><p>State the null and alternative hypotheses.</p></li>
<li><p>Compute the sample mean and standard deviation.</p></li>
<li><p>Conduct a one-sample <em>t</em>-test at the 5% significance level.</p></li>
<li><p>What do you conclude?</p></li>
<li><p>If the sample had been twice as large with the same mean and standard deviation, how would the <em>p</em>-value likely change?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li>The statement of the instructor is that the mean is <strong>less</strong> than 70 bpm, so that becomes our alternative hypothesis, and the opposite case becomes the null hypothesis. We use <span class="math inline">\(H_0: \mu=70\)</span> as we are only interested in the edge case when testing.</li>
</ol>
<p><span class="math inline">\(H_0: \mu = 70\)</span> <span class="math inline">\(H_1: \mu &lt; 70\)</span></p>
<ol start="2" type="a">
<li>We simply compute using the given data and</li>
</ol>
<p><span class="math inline">\(\bar{x} = \frac{1}{10}\sum^{10}_{i=1}x_i=68.0\)</span>, <span class="math inline">\(s=\sqrt{\frac{1}{n-1}\sum^{10}_{i=1}\left(x_i-\bar{x}\right)^2} \approx 2.58\)</span></p>
<ol start="3" type="a">
<li><p><span class="math inline">\(t = \frac{68 - 70}{2.58/\sqrt{10}} \approx -2.45\)</span></p></li>
<li><p>Critical value (df = n-1=9) at <span class="math inline">\(\alpha = 0.05\)</span> is approximately -1.833. This number can easily be found in a t-table, or by running some code to estimate it.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">### qt gives the quantile function for the</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># t distribution. We use 0.05 to find the </span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># critical value as this is a one sided test. </span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 9 is just the degrees of freedom </span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.t.ppf(<span class="op">-</span><span class="fl">0.05</span>, <span class="dv">9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>nan</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">### Underneath I am finding the p-value by </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># looking at the distribution function of </span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the t-distribution and plugging in the </span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># found t statistic. </span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.t.cdf(<span class="op">-</span><span class="fl">2.45</span>, <span class="dv">9</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.0183783590582972</code></pre>
</div>
</div>
<p>Since -2.58 &lt; -1.833, we reject <span class="math inline">\(H_0\)</span>, and thus conclude that the average bpm is less than 70.</p>
<ol start="5" type="a">
<li>With a larger sample, the standard error would decrease, leading to a larger magnitude of the test statistic and a <strong>smaller</strong> p-value. This illustrates the effect of sample size on power.</li>
</ol>
</details>
</section>
<section id="problem-1.6" class="level3">
<h3 class="anchored" data-anchor-id="problem-1.6">Problem 1.6</h3>
<p>Suppose a manufacturer claims their machine fills soda bottles with 500 ml of soda. You suspect it underfills. You collect a sample of 12 bottles and measure:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array([<span class="dv">498</span>, <span class="dv">495</span>, <span class="dv">497</span>, <span class="dv">496</span>, <span class="dv">499</span>, <span class="dv">498</span>, <span class="dv">494</span>, <span class="dv">496</span>, <span class="dv">495</span>, <span class="dv">497</span>, <span class="dv">496</span>, <span class="dv">495</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This problem and it’s solutions were made in R, but feel free to use an equivalent.</p>
<ol type="a">
<li><p>Test if the true mean is less than 500 ml using R.</p></li>
<li><p>Provide the <em>p</em>-value and interpret the result.</p></li>
<li><p>What assumption are you making about the distribution?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">### The t.test command let's you run a t.test by </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># simply adding the H_0 mean and specifying the</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># variant you'd liek to run. Here we test for </span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H_1: mu&lt;500 and H_0: mu=500 </span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>t_result <span class="op">=</span> stats.ttest_1samp(x, popmean<span class="op">=</span><span class="dv">500</span>, alternative<span class="op">=</span><span class="st">'less'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(t_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TtestResult(statistic=np.float64(-8.482095610516701), pvalue=np.float64(1.864450821881949e-06), df=np.int64(11))</code></pre>
</div>
</div>
<ol start="2" type="a">
<li><p>Output might give <span class="math inline">\(t \approx -8.49\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>. Strong evidence the machine underfills.</p></li>
<li><p>We assume that the population distribution is approximately normal, as required for small-sample <em>t</em>-tests.</p></li>
</ol>
</details>
</section>
</section>
<section id="two-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="two-sample-t-test">Two-sample t-test</h2>
<p>For the following exercises, we will use the test statistic for two-sample t-test with null hypothesis <span class="math inline">\(H_0:\mu_1=\mu_2+d_0\)</span>: <span class="math display">\[T=\frac{\bar x_1-\bar x_2-d_0}{\sqrt{s_1^2/n_1+s_2^2/n_2}},\]</span> where <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are the sample sizes of the two samples, <span class="math inline">\(\bar x_1\)</span> and <span class="math inline">\(\bar x_2\)</span> are the sample means, <span class="math inline">\(s_1\)</span> and <span class="math inline">\(s_2\)</span> are the sample standard deviations and <span class="math inline">\(d_0\)</span> is the difference in expected value under the null hypothesis (often <span class="math inline">\(d_0=0\)</span>). The test statistic follows a t-distribution with degrees of freedom (df): <span class="math display">\[\text{df}=\frac{\big(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}\big)^2}{\frac{(s_1^2/n_1)^2}{n_1-1}+\frac{(s_1^2/n_2)^2}{n_2-1}}\]</span></p>
<section id="problem-2.1" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.1">Problem 2.1</h3>
<p>An e-commerce company wants to test whether showing customer reviews on product pages increases the average number of purchases. Behavioral economics suggests that social proof (i.e., seeing others’ positive experiences) influences decision-making and can lead to higher sales.</p>
<p>To test this, the company randomly selected two groups of products: one group displayed customer reviews, and the other did not. They then compared the average daily sales per product between the two groups.</p>
<ol type="a">
<li><p>Set up the null- and alternative hypothesis. Use 10% significance level.</p></li>
<li><p>Discuss how the test statistic will behave under the various hypothesis.</p></li>
</ol>
<p>The experiment result in the following data:</p>
<ul>
<li><em>Products with reviews</em>: Sample mean daily sales = 120 units, Sample standard deviation = 30, Sample size = 40</li>
<li><em>Products without reviews</em>: Sample mean daily sales = 105 units, Sample standard deviation = 28, Sample size = 40</li>
</ul>
<ol start="3" type="a">
<li><p>Calculate the test statistic and the degrees of freedom.</p></li>
<li><p>Find the p-value. What is the conclusion?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<p>Let <span class="math inline">\(\mu_1\)</span> be the expected daily sales with reviews and <span class="math inline">\(\mu_2\)</span> without reviewes.</p>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu_1\le \mu_2\)</span> vs <span class="math inline">\(H_A: \mu_1&gt;\mu_2\)</span>.</p></li>
<li><p>Under the null hypothesis, we expect the numerator of the test statistic to be close to zero, making the test statistic close to zero. Under the alternative hypothesis, we expect <span class="math inline">\(\bar x_1&gt;\bar x_2\)</span> such that the numerator of <span class="math inline">\(T\)</span> will be positive. Higher values will therefore favor the alternative hypothesis.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> <span class="dv">30</span><span class="op">;</span>  s2 <span class="op">=</span> <span class="dv">28</span><span class="op">;</span> n1 <span class="op">=</span> <span class="dv">40</span><span class="op">;</span> n2 <span class="op">=</span> <span class="dv">40</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="op">=</span> <span class="dv">120</span><span class="op">;</span> m2 <span class="op">=</span> <span class="dv">105</span><span class="op">;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> (s1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1 <span class="op">+</span> s2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2)<span class="op">**</span><span class="dv">2</span><span class="op">/</span>((s1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1)<span class="op">**</span><span class="dv">2</span><span class="op">/</span>(n1<span class="op">-</span><span class="dv">1</span>)<span class="op">+</span>(s2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2)<span class="op">**</span><span class="dv">2</span><span class="op">/</span>(n2<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> (m1<span class="op">-</span>m2)<span class="op">/</span>np.sqrt(s1<span class="op">*</span>s1<span class="op">/</span>n1<span class="op">+</span>s2<span class="op">*</span>s2<span class="op">/</span>n2)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"df="</span>,df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>df= 77.63164160330635</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"T="</span>,t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T= 2.311799743112827</code></pre>
</div>
</div>
<p><span class="math inline">\(T=(102-105)/\sqrt{30^2/40+28^2/40}=-0.462\)</span> <span class="math display">\[\text{df}=\frac{\big(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}\big)^2}{\frac{(s_1^2/n_1)^2}{n_1-1}+\frac{(s_1^2/n_2)^2}{n_2-1}}\]</span></p>
<ol start="4" type="a">
<li><span class="math inline">\(\text{p-value}=P(T_{29}&gt;0.462)=0.32\)</span>. The p-value is lower than 10%, indicating that we may reject the null hypothesis. There is enough evidence to suggest that the reviews increase the sales at a 10% significance level. The company should show reviews of their products to increase sales.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.t.cdf(t, df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.011720746167147467</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-2.2" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.2">Problem 2.2</h3>
<p>A company is testing whether offering a performance-based bonus increases employee productivity. They implement a new bonus system in one office location (Group A), while another office continues without bonuses (Group B). After three months, they measure the average number of completed sales calls per week in both offices. The company wants you to determine if the bonus system leads to higher productivity (mean number of sales calls).</p>
<ol type="a">
<li>Formulate the hypothesis problem including <span class="math inline">\(H_0\)</span>, <span class="math inline">\(H_A\)</span> and setting a suitable significance level.</li>
</ol>
<p>Group A (Bonus group):</p>
<ul>
<li>Sample mean: 52 sales calls per week</li>
<li>Sample standard deviation: 8</li>
<li>Sample size: n = 35</li>
</ul>
<p>Group B (No bonus group):</p>
<ul>
<li>Sample mean: 48 sales calls per week</li>
<li>Sample standard deviation: 9</li>
<li>Sample size: n = 35</li>
</ul>
<ol start="2" type="a">
<li><p>Calculate the test statistic based on this information. Find the p-value.</p></li>
<li><p>What is your conclusion and your recommendation to the company?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu_A =\mu_B\)</span> vs <span class="math inline">\(H_A: \mu_A&gt;\mu_B\)</span>. In this case, the bonus scheme might be expensive, so we want to avoid type I errors (rejecting the null, when it is truly no difference in productivity). We use <span class="math inline">\(\alpha = 1\%\)</span>.</p></li>
<li><p><span class="math inline">\(T=1.96\)</span> and p-value <span class="math inline">\(=0.0267\)</span>.</p></li>
<li><p>The p-value is low, indicating evidence for the alternative hypothesis, but we have set a significance level of 1%, for which the p-value exceeds. This would lead us to not recommend implementing the bonus, because it does not improve productivity to a high enough degree at this significance level.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="op">=</span> <span class="dv">52</span><span class="op">;</span> s1 <span class="op">=</span> <span class="dv">8</span><span class="op">;</span> n1 <span class="op">=</span> <span class="dv">35</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="op">=</span> <span class="dv">48</span><span class="op">;</span> s2 <span class="op">=</span> <span class="dv">9</span><span class="op">;</span> n2 <span class="op">=</span> <span class="dv">35</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>stats.ttest_ind_from_stats(m1,s1,n1,m2,s2,n2,alternative<span class="op">=</span><span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ttest_indResult(statistic=np.float64(1.9652147377620703), pvalue=np.float64(0.026737892346682984))</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-2.3" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.3">Problem 2.3</h3>
<p>A university wants to determine if students who attend tutoring sessions perform better on exams than those who do not. Two independent samples of students were taken:</p>
<ul>
<li><em>Tutoring group</em>: Mean score = 78, Standard deviation = 10, Sample size = 30</li>
<li><em>Non-tutoring group</em>: Mean score = 72, Standard deviation = 12, Sample size = 35</li>
</ul>
<ol type="a">
<li><p>State the hypotheses.</p></li>
<li><p>Calculate the test statistic and degrees of freedom.</p></li>
<li><p>Find the p-value and interpret the result.</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> vs <span class="math inline">\(H_A: \mu_1 &gt; \mu_2\)</span>.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> <span class="dv">10</span><span class="op">;</span> s2 <span class="op">=</span> <span class="dv">12</span><span class="op">;</span> n1 <span class="op">=</span> <span class="dv">30</span><span class="op">;</span> n2 <span class="op">=</span> <span class="dv">35</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="op">=</span> <span class="dv">78</span><span class="op">;</span> m2 <span class="op">=</span> <span class="dv">72</span><span class="op">;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> (s1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1 <span class="op">+</span> s2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2)<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> ((s1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1)<span class="op">**</span><span class="dv">2</span><span class="op">/</span>(n1<span class="op">-</span><span class="dv">1</span>) <span class="op">+</span> (s2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2)<span class="op">**</span><span class="dv">2</span><span class="op">/</span>(n2<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> (m1<span class="op">-</span>m2) <span class="op">/</span> ((s1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1 <span class="op">+</span> s2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2)<span class="op">**</span><span class="fl">0.5</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"df="</span>, df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>df= 62.958820084919275</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"T="</span>, t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T= 2.1985812677253573</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>The computed p-value is <span class="math inline">\(P(T_{63}&gt;t)=0.0158\)</span>. The evidence thus points towards the conclusion that attending tutoring improves performance, due to a low p-value.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.t.cdf(t, df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.01579534729247911</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-2.4" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.4">Problem 2.4</h3>
<p>A professor wants to compare exam scores between online and in-person students, as he suspects his students preform systematically better with online exams. The results:</p>
<ul>
<li>Online: 82, 85, 88, 79, 84</li>
<li>In-person: 78, 74, 80, 76, 77</li>
</ul>
<ol type="a">
<li><p>Set up the hypotheses.</p></li>
<li><p>Conduct a two-sample <em>t</em>-test.</p></li>
<li><p>At the 0.05 significance level, what do you conclude?</p></li>
</ol>
<!-- d)  What might be the impact of unequal variances on this test? -->
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: \mu_{\text{online}} = \mu_{\text{in-person}}\)</span> <span class="math inline">\(H_1: \mu_{\text{online}} &gt; \mu_{\text{in-person}}\)</span></p></li>
<li><p>Compute sample means and the sample variances. For sample 1, being the online results.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">### We use the same methods as always to find the sample mean and variance, but here is a simple way to do it in R. I made this problem have very small datasets so it would be feasible to do by hand, so please make sure you find teh same results. </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>x_1 <span class="op">=</span> np.array([<span class="dv">82</span>, <span class="dv">85</span>, <span class="dv">88</span>, <span class="dv">79</span>, <span class="dv">84</span>])</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>mean_x1 <span class="op">=</span> np.mean(x_1)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>var_x1 <span class="op">=</span> np.var(x_1,ddof<span class="op">=</span><span class="dv">1</span>)  </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Mean:"</span>, mean_x1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 83.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variance:"</span>, var_x1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variance: 11.299999999999999</code></pre>
</div>
</div>
<p>I.e., we end up with <span class="math inline">\(\bar{x}_1=83.6\)</span> and <span class="math inline">\(s^2_1=11.3\)</span></p>
<p>Now for sample 2, in person.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">### Same as above, just new names</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>x_2 <span class="op">=</span> np.array([<span class="dv">78</span>, <span class="dv">74</span>, <span class="dv">80</span>, <span class="dv">76</span>, <span class="dv">77</span>])</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>mean_x2 <span class="op">=</span> np.mean(x_2)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>var_x2 <span class="op">=</span> np.var(x_2,ddof<span class="op">=</span><span class="dv">1</span>)  </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Mean:"</span>, mean_x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean: 77.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variance:"</span>, var_x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variance: 5.0</code></pre>
</div>
</div>
<p>I.e., we end up with <span class="math inline">\(\bar{x}_1=77\)</span> and <span class="math inline">\(s^2_1=5\)</span></p>
<p>Test statistic:</p>
<p><span class="math display">\[
t = \frac{83.6 - 77.0}{\sqrt{\left(11.3/5+5/5\right)}} \approx 3.6554
\]</span></p>
<ol start="3" type="a">
<li>This is a one sided, and now we only need find the degrees of freedom to determine the proper critical value.</li>
</ol>
<p><span class="math display">\[
\text{df}=\frac{\left(11.3/5+5/5\right)^2}{\frac{(11.3/5)^2}{4}+\frac{(5/5)^2}{4}}=6.9602\approx7
\]</span> Using a table we can find our critical value when we let the df be 7 is 1.895.</p>
<p>With this we reject <span class="math inline">\(H_0\)</span>, significant difference.</p>
<p>Being more exact we can use some simple Python code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">### Since we are using a "greater than" test we need to use the 0.95 quantile to find the proper critical value, but since the t-distribution is symmetric, 0.95 and 0.05 will only be separated by a minus sign. </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.t.ppf(<span class="fl">0.95</span>, df <span class="op">=</span> <span class="fl">6.9602</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.8962097832217037</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">### The probability function finds the finds the probability of being under a value, we here take the complement to find the probability of being over 3.6554</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.t.cdf(<span class="fl">3.6554</span>, <span class="fl">6.9602</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.004100373037377536</code></pre>
</div>
</div>
<p>Underneath is an example of python code to do the exact same test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>x_1 <span class="op">=</span> np.array([<span class="dv">82</span>, <span class="dv">85</span>, <span class="dv">88</span>, <span class="dv">79</span>, <span class="dv">84</span>])</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>x_2 <span class="op">=</span> np.array([<span class="dv">78</span>, <span class="dv">74</span>, <span class="dv">80</span>, <span class="dv">76</span>, <span class="dv">77</span>])</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sided t-test: H1 is that mean of x_1 &gt; mean of x_2</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> stats.ttest_ind(x_1, x_2, equal_var<span class="op">=</span><span class="va">False</span>, alternative<span class="op">=</span><span class="st">'greater'</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"t-statistic:"</span>, result.statistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 3.6554019191032916</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"p-value:"</span>, result.pvalue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value: 0.004100315140564395</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-2.5" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.5">Problem 2.5</h3>
<p>Suppose a two-sample <em>t</em>-test yields a <em>p</em>-value of 0.045 for comparing the means of two groups, using a significance level of 0.05.</p>
<ol type="a">
<li><p>Can we say the means are “significantly different”?</p></li>
<li><p>What if the significance level had been 0.01 instead?</p></li>
<li><p>Explain how this relates to Type I error.</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>Yes — at <span class="math inline">\(\alpha = 0.05\)</span>, we reject <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>No — we would not reject at <span class="math inline">\(\alpha = 0.01\)</span>.</p></li>
<li><p>Significance thresholds control the probability of a Type I error (rejecting a true <span class="math inline">\(H_0\)</span>). A lower threshold is more conservative.</p></li>
</ol>
</details>
</section>
<section id="problem-2.6" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.6">Problem 2.6</h3>
<p>Two teachers use different methods to teach the same material, and they want to test if their methods give different average results. Students are randomly assigned to either class.</p>
<ul>
<li><strong>Group A</strong> (n = 10): Mean = 78, SD = 6</li>
<li><strong>Group B</strong> (n = 14): Mean = 73, SD = 10</li>
</ul>
<ol type="a">
<li><p>State the hypotheses.</p></li>
<li><p>Calculate the Welch <em>t</em>-statistic.</p></li>
<li><p>Estimate the degrees of freedom.</p></li>
<li><p>Test at the 5% level: is there a significant difference in mean scores?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>We have no indication of directionality for this test. Thus we end up with the following null and alternative hypotheses.<br>
<span class="math inline">\(H_0: \mu_A = \mu_B\)</span> <span class="math inline">\(H_1: \mu_A \ne \mu_B\)</span></p></li>
<li><p>We can plug i the means, square the standard deviatons and plug in the numbers in each sample for the test statistic. <span class="math display">\[
t = \frac{78 - 73}{\sqrt{6^2/10 + 10^2/14}} = \frac{5}{\sqrt{3.6 + 7.14}} = \frac{5}{\sqrt{10.74}} \approx 1.53
\]</span></p></li>
<li></li>
</ol>
<p><span class="math display">\[
df \approx \frac{(10.74)^2}{(3.6^2/9 + 7.14^2/13)} \approx 21.51
\]</span></p>
<ol start="4" type="a">
<li>At <span class="math inline">\(df = 22\)</span>, two-tailed 5% critical <em>t</em> ≈ ±2.074. (found in table for critical values) Since 1.52 &lt; 2.08, we <strong>fail to reject</strong> <span class="math inline">\(H_0\)</span>.</li>
</ol>
<p>Using Python code we can also find the exact and approximate df.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">## lower and upper bound for approximate df</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>stats.t.ppf(<span class="fl">0.025</span>, <span class="dv">22</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(-2.073873067904015)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>stats.t.ppf(<span class="fl">0.975</span>, <span class="dv">22</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(2.0738730679040147)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">## for exact df</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>stats.t.ppf(<span class="fl">0.025</span>, <span class="fl">21.51</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(-2.076615611268758)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>stats.t.ppf(<span class="fl">0.975</span>, <span class="fl">21.51</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(2.076615611268758)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co">## Note that the lower and upper bounds have the same absolute value. This is a consequence of the t-distribution being symmetric. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</details>
</section>
<section id="problem-2.7" class="level3">
<h3 class="anchored" data-anchor-id="problem-2.7">Problem 2.7</h3>
<p>You are given two samples:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.array([<span class="dv">85</span>, <span class="dv">87</span>, <span class="dv">83</span>, <span class="dv">84</span>, <span class="dv">89</span>, <span class="dv">91</span>])</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> np.array([<span class="dv">78</span>, <span class="dv">77</span>, <span class="dv">79</span>, <span class="dv">81</span>, <span class="dv">76</span>, <span class="dv">75</span>, <span class="dv">80</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="a">
<li><p>Conduct a two-sample <em>t</em>-test assuming unequal variances.</p></li>
<li><p>Report the <em>t</em>-statistic, degrees of freedom, and <em>p</em>-value.</p></li>
<li><p>Interpret the result at <span class="math inline">\(\alpha=0.05\)</span>.</p></li>
<li><p>Does the output indicate anything about equality of variances?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li>We can use a simplePythoncommand for this</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> stats.ttest_ind(A, B, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TtestResult(statistic=np.float64(5.666666666666667), pvalue=np.float64(0.00033388838046637467), df=np.float64(8.797264682220435))</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>From, the test summary we can just read</li>
</ol>
<p><span class="math display">\[
t=5.6667 \quad
df=8.793 \quad
\text{p-value}=0.0003339
\]</span></p>
<ol start="3" type="a">
<li><p>Strong evidence against <span class="math inline">\(H_0\)</span> in form of such a low p-value, this indicates that the two samples are different at a 5 percent significance level.</p></li>
<li><p>Welch’s <em>t</em>-test does <strong>not require equal variances</strong> and is safer when variances are not assumed equal.</p></li>
</ol>
</details>
</section>
</section>
<section id="tests-of-proportions-one-sample" class="level2">
<h2 class="anchored" data-anchor-id="tests-of-proportions-one-sample">Tests of proportions: One sample</h2>
<p>Let <span class="math inline">\(p\)</span> denote a proportion and <span class="math inline">\(p_0\)</span> be the proportion under the null hypothesis. We can then test the null hypothesis <span class="math inline">\(H_0: p=p_0\)</span> against an alternative hypothesis using the test statistic <span class="math display">\[Z = \frac{\hat p-p_0}{\sqrt{p_0(1-p_0)/n}},\]</span> which is approximately normally distributed when <span class="math inline">\(n\)</span> is sufficiently large and the probabilies are not too small (often <span class="math inline">\(np&gt;5\)</span> is used as a rule of thumb).</p>
<section id="problem-3.1" class="level3">
<h3 class="anchored" data-anchor-id="problem-3.1">Problem 3.1</h3>
<p>A retail chain is considering phasing out cash payments in favor of digital transactions. Management wants to determine whether at least 60% of customers are already using mobile payment apps (such as Apple Pay or Google Pay) when shopping. If the proportion is significantly higher than 60%, they may move forward with reducing cash payment options.</p>
<ol type="a">
<li>Set up the null hypothesis and alternative hypothesis. Discuss how the test statistic will behave under the various hypotheses.</li>
</ol>
<p>The retail chain conducts a survey where they ask customers whether they used a mobile payment app for their most recent purchase. Out of the 400 customers asked, 260 used mobile payment apps.</p>
<ol start="2" type="a">
<li><p>Calculate <span class="math inline">\(Z\)</span> based on this information. What is the p-value?</p></li>
<li><p>What does the p-value tell you about people’s payment preferences?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: p=0.6\)</span> vs <span class="math inline">\(H_A: \mu&gt;0.6\)</span>. The numerator of <span class="math inline">\(Z\)</span> will be expected close to 0 if the null is zero, making Z close to zero. If <span class="math inline">\(H_A\)</span> is true, <span class="math inline">\(\widehat p\)</span> will be expected larger than 0.6, making Z positive. Large values of <span class="math inline">\(Z\)</span> will favor <span class="math inline">\(H_A\)</span>.</p></li>
<li><p><span class="math inline">\(Z = (0.65-0.6)/\sqrt{0.6\cdot 0.4/400}=2.04\)</span> and p-value<span class="math inline">\(=P(Z&gt;2.04)=0.0206\)</span>.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>phat <span class="op">=</span> <span class="dv">260</span><span class="op">/</span><span class="dv">400</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (phat<span class="op">-</span><span class="fl">0.6</span>)<span class="op">/</span>np.sqrt(<span class="fl">0.6</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="fl">0.6</span>)<span class="op">/</span><span class="dv">400</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Z="</span>, z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z= 2.041241452319317</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Pvalue: "</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pvalue:  0.02061341666858174</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>The p-value is low, which indicates evidence against <span class="math inline">\(H_0\)</span>. It indicates that the proportion of mobile app payments is above 60%.</li>
</ol>
</details>
</section>
<section id="problem-3.2" class="level3">
<h3 class="anchored" data-anchor-id="problem-3.2">Problem 3.2</h3>
<p>A sustainable fashion brand wants to know whether at least 30% of consumers are willing to pay a premium for eco-friendly clothing. If the proportion is significantly higher than 30% with significance level 10%, they will launch a new premium-priced, eco-friendly clothing line.</p>
<p>They conduct a market survey where respondents indicate whether they would be willing to pay 10% more for sustainably produced clothing.</p>
<ol type="a">
<li>Set up the null- and alternative hypothesis.</li>
</ol>
<p>The market survey got 500 respondents, and out of those, 166 were willing to pay 10% more for sustainable clothing.</p>
<ol start="2" type="a">
<li><p>Calculate <span class="math inline">\(Z\)</span> based on this information. What is the p-value?</p></li>
<li><p>What would your recommendation to the fashion brand be?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: p\le 30\%\)</span> vs <span class="math inline">\(H_A: p&gt;30\%\)</span>.</p></li>
<li><p><span class="math inline">\(\hat p=166/500= 33.2\%\)</span>, <span class="math inline">\(z=(0.332-0.3)/\sqrt{0.3*0.7/500}=1.56\)</span> and <span class="math inline">\(P(Z&gt;z)=P(Z&gt;1.56)=1-\Phi(1.56)=0.0592\)</span>.</p></li>
<li><p>At a 10% signifance level, we would reject the null hypothesis, since the p-value of 0.06 is smaller than 0.1. At this significance level, we would recommend the brand to go ahead with the launch of their eco-friendly clothing.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>phat <span class="op">=</span> <span class="dv">166</span><span class="op">/</span><span class="dv">500</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (phat<span class="op">-</span><span class="fl">0.3</span>)<span class="op">/</span>np.sqrt(<span class="fl">0.3</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="fl">0.3</span>)<span class="op">/</span><span class="dv">500</span>)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Z="</span>, z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z= 1.5614401167176546</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Pvalue: "</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pvalue:  0.05920997135406203</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-3.3" class="level3">
<h3 class="anchored" data-anchor-id="problem-3.3">Problem 3.3</h3>
<p>A public transportation agency wants to determine whether at least 70% of residents support a new subway line expansion. A survey of 600 residents finds that 435 support the expansion.</p>
<ol type="a">
<li><p>Formulate the hypotheses.</p></li>
<li><p>Compute the test statistic and p-value.</p></li>
<li><p>What is the conclusion?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: p = 0.7\)</span> vs <span class="math inline">\(H_A: p &gt; 0.7\)</span>.</p></li>
<li><p><span class="math display">\[Z=\frac{0.725-0.7}{\sqrt{0.7\cdot 0.3/600}}=1.63\]</span></p></li>
</ol>
<p>p-value <span class="math inline">\(=P(Z&gt;1.63)=0.0907\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> <span class="dv">435</span><span class="op">/</span><span class="dv">600</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (p_hat<span class="op">-</span><span class="fl">0.7</span>) <span class="op">/</span> ( (<span class="fl">0.7</span><span class="op">*</span><span class="fl">0.3</span><span class="op">/</span><span class="dv">600</span>)<span class="op">**</span><span class="fl">0.5</span> )</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Z="</span>, z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z= 1.336306209562123</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"p-value="</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value= 0.09072460386070991</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>A p-value of 9% indicates that the evidence against the null hypothesis is not very strong, and at a 5% significance level, we would not reject the null hypothesis.</li>
</ol>
</details>
</section>
<section id="problem-3.4" class="level3">
<h3 class="anchored" data-anchor-id="problem-3.4">Problem 3.4</h3>
<p>A factory claims that at most 5% of products are defective. In a random sample of 80 products, 7 were defective.</p>
<ol type="a">
<li><p>Test whether the true defect rate is higher than claimed at the 5% level.</p></li>
<li><p>Compute the test statistic.</p></li>
<li><p>Conclude and interpret.</p></li>
<li><p>Should we consider this test trustworthy</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li>Since we want to explore if the proportion of defectives is <strong>higher</strong> than 5%, let’s make that our alternative hypothesis.<br>
<span class="math inline">\(H_0: p = 0.05\)</span>,</li>
</ol>
<p><span class="math inline">\(H_1: p &gt; 0.05\)</span></p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[
\hat{p} = \frac{7}{80} = 0.0875,\quad z = \frac{0.0875 - 0.05}{\sqrt{0.05(0.95)/80}} \approx 1.54
\]</span></p>
<ol start="3" type="a">
<li></li>
</ol>
<p>Since our alternative hypothesis is that that <span class="math inline">\(p&gt;0.05\)</span> we would need z to be <strong>higher</strong> than some critical value at the 5% level. Since we are using a one-sided test here, we find in a table that the critical value is given by <span class="math inline">\(z\approx 1.645\)</span>. We can clearly tell that our test-statistic is not hihgh enough and this we won’t discard <span class="math inline">\(H_0\)</span> in this case. Underneath I have done some computation giving a more exact critical value and finding the p-value is about 6 percent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.norm.ppf(<span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.6448536269514722</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.norm.cdf(<span class="fl">1.54</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.06178017671181191</code></pre>
</div>
</div>
<ol start="4" type="a">
<li></li>
</ol>
<p>The common rule of thumb is <span class="math inline">\(np&gt;5\)</span>, and since <span class="math inline">\(n\hat{p}=7\)</span> in this case, we find little reason for doubt in this case.</p>
</details>
</section>
</section>
<section id="tests-of-proportions-two-samples" class="level2">
<h2 class="anchored" data-anchor-id="tests-of-proportions-two-samples">Tests of proportions: Two samples</h2>
<p>Let <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> denote two proportions. We can then test the null hypothesis <span class="math inline">\(H_0: p_1=p_2\)</span> against an alternative hypothesis using the test statistic <span class="math display">\[Z = \frac{\hat p_1-\hat p_2}{\sqrt{p_\text{pool}(1-p_\text{pool})(1/n_1+1/n_2)}},\]</span> where <span class="math display">\[p_\text{pool}=\frac{n_1\widehat p_1+n_2\widehat p_2}{n_1+n_2}.\]</span> The test statistic Z is approximately normally distributed.</p>
<section id="problem-4.1" class="level3">
<h3 class="anchored" data-anchor-id="problem-4.1">Problem 4.1</h3>
<p>An insurance company is testing how the way they frame their sales pitch affects customers’ willingness to buy a travel insurance policy. They randomly assign potential customers into two groups:</p>
<ol type="1">
<li>Loss-framed message: “If you don’t buy travel insurance, you could lose thousands in unexpected expenses.”</li>
<li>Gain-framed message: “If you buy travel insurance, you’ll have peace of mind and financial protection.”</li>
</ol>
<p>Behavioral economics suggests that loss aversion makes people more sensitive to potential losses than gains, meaning the loss-framed message might lead to higher purchase rates.</p>
<ol type="a">
<li><p>Set up the null- and alternative hypothesis.</p></li>
<li><p>Discuss how the test statistic will behave under the various hypothesis.</p></li>
</ol>
<p>The experiment result in the following data:</p>
<ul>
<li><em>Loss-framed message</em>: 200 customers surveyed, 45% purchased insurance</li>
<li><em>Gain-framed message</em>: 200 customers surveyed, 35% purchased insurance</li>
</ul>
<ol start="3" type="a">
<li><p>Calculate the test statistic and the p-value.</p></li>
<li><p>Conclude the test.</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<p>Let <span class="math inline">\(p_L\)</span> denote proportion of purchases receiving a loss-framed message and <span class="math inline">\(p_G\)</span> denote proportion of purchases receiving a gain-framed message. a) <span class="math inline">\(H_0: p_L=p_G\)</span> vs <span class="math inline">\(H_A: p_L&gt;p_G\)</span>.</p>
<ol start="2" type="a">
<li><p>We use <span class="math inline">\(p_1=p_L\)</span> and <span class="math inline">\(p_2 =p_G\)</span> in refence to the formula for the test statistic. If the null hypothesis is true, Z is expected to be close to zero since the numerator is expected to be near 0. If the alternative hypothesis is true, we expect <span class="math inline">\(\hat p_L&gt;\hat p_G\)</span>, giving a positive numerator. Thus, large values of Z will favor the alternative hypothesis.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>pL <span class="op">=</span> <span class="fl">0.45</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>pG <span class="op">=</span> <span class="fl">0.35</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>nL <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>nG <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>pPool <span class="op">=</span> (nL<span class="op">*</span>pL <span class="op">+</span> nG<span class="op">*</span>pG)<span class="op">/</span>(nL<span class="op">+</span>nG)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (pL<span class="op">-</span>pG)<span class="op">/</span>np.sqrt(pPool<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pPool)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span>nL<span class="op">+</span><span class="dv">1</span><span class="op">/</span>nG))</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Z="</span>,z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z= 2.041241452319316</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"pvalue="</span>,<span class="dv">1</span><span class="op">-</span>stats.norm.cdf(z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pvalue= 0.02061341666858174</code></pre>
</div>
</div>
<ol start="4" type="a">
<li>The p-value is low (around 2%). This indicates that the probability of making a Type I error is low and favor rejecting the null hypothesis. In that sense, the evidence points towards people being willing to pay to avoid loss than they are to potentially gain.</li>
</ol>
</details>
</section>
<section id="problem-4.2" class="level3">
<h3 class="anchored" data-anchor-id="problem-4.2">Problem 4.2</h3>
<p>An online retailer wants to determine whether offering free shipping increases the proportion of customers who complete their purchases. They run an A/B test, where one group of customers sees free shipping on all orders (Group A), while another group sees the standard shipping fees (Group B). After a week, they compare the proportion of customers who completed a purchase in each group. The retailer asks you to use 5% significance level.</p>
<ol type="a">
<li>Formulate the hypothesis problem.</li>
</ol>
<p>For the two groups, the retailer gathered the following data:</p>
<p>Group A (Standard shipping):</p>
<ul>
<li>Sample size: 469</li>
<li>Completed purchases: 191</li>
</ul>
<p>Group B (Free shipping)</p>
<ul>
<li>Sample size: 483</li>
<li>Completed purchases: 231</li>
</ul>
<ol start="2" type="a">
<li><p>Perform the test: Find Z and the p-value.</p></li>
<li><p>What is your conclusion?</p></li>
<li><p>The chief economist in the company has taken a statistics course and learned about the difference between statistical significance and economical significance. How would this distinction influence your recommendation to the company?</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: p_A=p_B\)</span> vs <span class="math inline">\(H_A: p_A&lt;p_B\)</span>.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>nA <span class="op">=</span> <span class="dv">469</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>nB <span class="op">=</span> <span class="dv">483</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>pA <span class="op">=</span> <span class="dv">191</span><span class="op">/</span>nA</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>pB <span class="op">=</span> <span class="dv">231</span><span class="op">/</span>nB</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pB<span class="op">-</span>pA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.07101140261425792</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>pPool <span class="op">=</span> (nA<span class="op">*</span>pA <span class="op">+</span> nB<span class="op">*</span>pB)<span class="op">/</span>(nA<span class="op">+</span>nB)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (pA<span class="op">-</span>pB)<span class="op">/</span>np.sqrt(pPool<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pPool)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span>nA<span class="op">+</span><span class="dv">1</span><span class="op">/</span>nB))</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Z="</span>,z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z= -2.2050192819722274</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"pvalue="</span>,stats.norm.cdf(z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pvalue= 0.01372637075205902</code></pre>
</div>
</div>
<ol start="3" type="a">
<li><p>At a 5% significance level, the free shipping group have a higher completing rate than the standard shipping group.</p></li>
<li><p>Here the effect size <span class="math inline">\(|\widehat p_A-\widehat p_B| = 7\%\)</span>, that is 7 percentage points higher rate of completing the order if the shipping is free. This increase in completed orders increases the volume, but the free shipping will reduce the margin on each order. We would need more information to assess whether this specific experiment that resulted in a statistically significant increase in volume, also resulted in a economically significant increase of profits.</p></li>
</ol>
</details>
</section>
<section id="problem-4.3" class="level3">
<h3 class="anchored" data-anchor-id="problem-4.3">Problem 4.3</h3>
<p>A company is testing whether a new website layout increases the proportion of users who complete a purchase. They conduct an A/B test with the following results:</p>
<ul>
<li><em>New layout</em>: 500 users, 210 completed a purchase</li>
<li><em>Old layout</em>: 500 users, 180 completed a purchase</li>
</ul>
<ol type="a">
<li><p>Formulate the hypotheses.</p></li>
<li><p>Compute the test statistic and p-value.</p></li>
<li><p>Interpret the result.</p></li>
</ol>
<details>
<summary>
Show solutions
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: p_1 = p_2\)</span> vs <span class="math inline">\(H_A: p_1 &gt; p_2\)</span>.</p></li>
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>n1, n2 <span class="op">=</span> <span class="dv">500</span>, <span class="dv">500</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>p1, p2 <span class="op">=</span> <span class="dv">210</span><span class="op">/</span>n1, <span class="dv">180</span><span class="op">/</span>n2</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>p_pool <span class="op">=</span> (<span class="dv">210</span> <span class="op">+</span> <span class="dv">180</span>) <span class="op">/</span> (n1 <span class="op">+</span> n2)</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (p1 <span class="op">-</span> p2) <span class="op">/</span> ((p_pool <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_pool) <span class="op">*</span> (<span class="dv">1</span><span class="op">/</span>n1 <span class="op">+</span> <span class="dv">1</span><span class="op">/</span>n2)) <span class="op">**</span> <span class="fl">0.5</span>)</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Z="</span>, z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z= 1.9450198311991271</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"p-value="</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(z))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value= 0.025886295779031898</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Since the p-value is low, this gives reason to doubt the null hypothesis and indicates that the new layout do increase the proportion of customers placing an order.</li>
</ol>
</details>
</section>
<section id="problem-4.4" class="level3">
<h3 class="anchored" data-anchor-id="problem-4.4">Problem 4.4</h3>
<p>In a clinical trial, 35 of 50 patients in group A responded to a vaccine. In group B, 40 of 60 patients responded.</p>
<ol type="a">
<li><p>State the hypotheses</p></li>
<li><p>Compute the test statistic</p></li>
<li><p>Conclude on the test</p></li>
<li><p>Interpret the result.</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p><span class="math inline">\(H_0: p_A = p_B\)</span>, <span class="math inline">\(H_a: p_A \ne p_B\)</span></p></li>
<li></li>
</ol>
<p><span class="math display">\[
\hat{p}_1 =\frac{35}{50}= 0.70,\quad \hat{p}_2=\frac{40}{60} = 0.6667,\quad \hat{p}_{\text{pooled}} = \frac{35+40}{110} = 0.6818
\]</span></p>
<p><span class="math display">\[
z = \frac{0.70 - 0.6667}{\sqrt{0.6818(1 - 0.6818)(1/50 + 1/60)}} \approx 0.373
\]</span></p>
<ol start="3" type="a">
<li>We know that test statistic should be normally distributed in this case. To reject the two sided test we would need <span class="math inline">\(|z|&gt;1.96\)</span>, which we clearly see isn’t the case, and we thus fail to reject <span class="math inline">\(H_0\)</span>.</li>
</ol>
<p>Let’s find the p-value with Python to show this clearly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Upper and lower bounds</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.norm.ppf(<span class="fl">0.025</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-1.9599639845400545</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.norm.ppf(<span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.959963984540054</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Computing p value</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">-</span>stats.norm.cdf(<span class="fl">0.373</span>)<span class="op">+</span>stats.norm.cdf(<span class="op">-</span><span class="fl">0.373</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.7091484439599731</code></pre>
</div>
</div>
<p><span class="math inline">\(p \approx 0.70\)</span>, not significant.</p>
<ol start="4" type="a">
<li>There is no evidence to suggest a difference in proportions.</li>
</ol>
</details>
</section>
</section>
<section id="normal-distribution-and-student-t-dsitribution" class="level2">
<h2 class="anchored" data-anchor-id="normal-distribution-and-student-t-dsitribution">Normal distribution and student t dsitribution</h2>
<section id="problem-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-1">Problem 1</h3>
<ol type="a">
<li><p>What are the two parameters that define a normal distribution?</p></li>
<li><p>What does the empirical rule (68-95-99.7 rule) state about the normal distribution?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>A normal distribution is fully defined by its <strong>mean (μ)</strong> and <strong>standard deviation (σ)</strong>.</p></li>
<li><p>The normal distribution is a symmetric distribution around its mean, <span class="math inline">\(\mu\)</span>. The rule gives an approximate measure of what proportion of the data that lies within a certain range of the mean.</p></li>
</ol>
<ul>
<li>~68% of data lie within 1σ of the mean</li>
<li>~95% within 2σ</li>
<li>~99.7% within 3σ</li>
</ul>
<p>This helps assess spread and typicality.</p>
</details>
</section>
<section id="problem-2" class="level3">
<h3 class="anchored" data-anchor-id="problem-2">Problem 2</h3>
<p>Given that <span class="math inline">\(X \sim \mathcal{N}(100, 15^2)\)</span> (i.e.&nbsp;<span class="math inline">\(X\)</span> is normally distributed with mean <span class="math inline">\(\mu=100\)</span> and standard deviation <span class="math inline">\(\sigma=15\)</span>), calculate:</p>
<ol type="a">
<li><p>The probability of <span class="math inline">\(X &lt; 100\)</span>. Why do we not need to consider the standard deviation when calculating this?</p></li>
<li><p>The approximate probability that <span class="math inline">\(X &lt; 115\)</span></p></li>
<li><p>Use a z-transformation to b) to standard normal, and compute using a calculator. Let <span class="math inline">\(Z\sim \mathcal{N}(0,1)\)</span>, we call that a standard normal distribution. We also have that</p></li>
</ol>
<p><span class="math display">\[
Z=\frac{X-\mu}{\sigma}
\]</span></p>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li>We know that the normal distribution is symmetric around the mean, i.e.&nbsp;we have a 50-50 chance of finding an <span class="math inline">\(X\)</span> above or below the mean. The mean here is 100, and was such we get</li>
</ol>
<p><span class="math display">\[
P(X&gt;100)=\frac{1}{2}=0.5
\]</span></p>
<ol start="2" type="a">
<li>We can use the 68-95-99.7 rule to find the approximate probability. 115 is one standard deviation greater than the mean. That means we have to account for <strong>half</strong> of the 68% from the rule. I.e.</li>
</ol>
<p><span class="math display">\[
P(X\in(100,115))=\frac{0.68}{2}\approx0.34
\]</span> Now let’s also account for the cases where <span class="math inline">\(X\leq 100\)</span></p>
<p><span class="math display">\[
P(X&lt;115)=P(X\leq100)+P(X\in(100,115))\approx0.5+0.34=0.84
\]</span> Note: Since the normal distribution is <strong>continuous</strong> <span class="math inline">\(P(X&lt;x)=P(X\leq x)\)</span></p>
<ol start="3" type="a">
<li><span class="math display">\[
P(X&lt;115)=P\left(\frac{Z-100}{15}&lt;\frac{115-100}{15}\right)=P(Z&lt;1)=0.8413
\]</span></li>
</ol>
<p><strong>Interpretation</strong>: There’s about an 84.13% chance that <span class="math inline">\(X\)</span> will be below 115, which is equivalent to <span class="math inline">\(Z\)</span> being below 1.</p>
</details>
</section>
<section id="problem-3" class="level3">
<h3 class="anchored" data-anchor-id="problem-3">Problem 3</h3>
<p>Suppose a random variable <span class="math inline">\(X \sim \mathcal{N}(\mu, \sigma^2)\)</span>. Show that:</p>
<p><span class="math display">\[
P(a &lt; X &lt; b) = P\left( \frac{a - \mu}{\sigma} &lt; Z &lt; \frac{b - \mu}{\sigma} \right)
\]</span></p>
<details>
<summary>
Show solution
</summary>
<p>This transformation uses the <strong>standardization</strong>:</p>
<p><span class="math display">\[
Z = \frac{X - \mu}{\sigma}
\]</span></p>
<p>By applying this, we shift any normal distribution to the standard normal. We need only substitute and solve like a regular inequality, and the equivalence becomes clear.</p>
<p><span class="math display">\[
P(a &lt; X &lt; b) = P\left( \frac{a - \mu}{\sigma} &lt; Z &lt; \frac{b - \mu}{\sigma} \right)
\]</span></p>
</details>
</section>
<section id="problem-4" class="level3">
<h3 class="anchored" data-anchor-id="problem-4">Problem 4</h3>
<ol type="a">
<li>Use the symmetry of the standard normal distribution to explain why:</li>
</ol>
<p><span class="math display">\[
P(Z &gt; 1.96) = P(Z &lt; -1.96)
\]</span></p>
<ol start="2" type="a">
<li>Calculate <span class="math inline">\(P(|Z| &gt; 1.96)\)</span></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li>The standard normal is symmetric about 0, so:</li>
</ol>
<p><span class="math display">\[
P(Z &gt; c) = P(Z &lt; -c)
\]</span> This equality comes from the logical fact of us a random varabiable being just as unlikely to take a value beyond a certain distance from the mean, no matter if the distance is in a positive of a negative directoion.</p>
<ol start="2" type="a">
<li></li>
</ol>
<p><span class="math display">\[
P(|Z| &gt; 1.96) =P(Z&lt;-1.96))+P(Z&gt;1.96)=2P(Z&lt;-1.96)\approx 2*0.025=0.05
\]</span></p>
</details>
</section>
<section id="problem-5" class="level3">
<h3 class="anchored" data-anchor-id="problem-5">Problem 5</h3>
<ol type="a">
<li><p>Sketch or describe how the <em>t</em>-distribution changes as degrees of freedom increase.</p></li>
<li><p>What does the <em>t</em>-distribution converge to?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>With low degrees of freedom, the <em>t</em>-distribution is flatter and has fatter tails. As df increases, it becomes more peaked. The t-distribution also always has a mean of 0, and is symmetric around 0.</p></li>
<li><p>As df → ∞, the <em>t</em>-distribution approaches the <strong>standard normal distribution</strong>.</p></li>
</ol>
<p>We can illustrate this quite simply without going into the ideas fully.</p>
<p>Let first <span class="math inline">\(X_1,\dots,X_n\sim i.i.d. \mathcal{N}(\mu, \sigma^2)\)</span>, and then let</p>
<p><span class="math display">\[ \bar{X}=\frac{1}{n}\sum^n_{i=1}X_i, \quad S^2=\frac{1}{n-1}\sum^n_{i=1}(X_i-\bar{X})^2
\]</span> It can then be shown that <span class="math display">\[ \frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1), \quad \frac{\bar{X}-\mu}{S/\sqrt{n}}\sim t\_{n-1} \]</span> where <span class="math inline">\(t_{n-1}\)</span> indicates a t-distribution with <span class="math inline">\(df=n-1\)</span>. Clearly these are very similar statements. All we need to recall now is that <span class="math inline">\(S^2\)</span> is and unbiased and consistent estimator of <span class="math inline">\(\sigma^2\)</span>. I.e.</p>
<p><span class="math display">\[
\lim_{n\rightarrow\infty}S^2=\sigma^2 \quad  \Rightarrow \quad  \frac{\bar{X}-\mu}{S/\sqrt{n}}\sim t_{n-1} \rightarrow \frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1).
\]</span></p>
</details>
</section>
<section id="problem-6" class="level3">
<h3 class="anchored" data-anchor-id="problem-6">Problem 6</h3>
<p>A population has a skewed distribution with mean 10 and SD 5. Suppose we take samples of size 50. You can assume the samples are iid.</p>
<ol type="a">
<li><p>What is the expected distribution of the sample mean?</p></li>
<li><p>Use CLT to approximate <span class="math inline">\(P(\bar{X} &gt; 11)\)</span></p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>CLT tells us that <span class="math inline">\(\bar{X} \sim \mathcal{N}\left(10, \frac{5}{\sqrt{50}}\right)\)</span></p></li>
<li></li>
</ol>
<p><span class="math display">\[
Z = \frac{11 - 10}{5/\sqrt{50}} \approx \frac{1}{0.707} \approx 1.41
\Rightarrow P(Z &gt; 1.41) \approx 0.079
\]</span></p>
</details>
</section>
<section id="problem-7" class="level3">
<h3 class="anchored" data-anchor-id="problem-7">Problem 7</h3>
<p>Explain when you should use the standard normal vs.&nbsp;the <em>t</em>-distribution in practice.</p>
<details>
<summary>
Show solution
</summary>
<p>Use the <strong>t-distribution</strong> if:</p>
<ul>
<li>Population standard deviation is unknown</li>
<li>Sample size is small (typically n &lt; 30)</li>
</ul>
<p>Use <strong>standard normal</strong> if:</p>
<ul>
<li>Population SD is known, or n is large, such that CLT becomes viable.</li>
</ul>
</details>
</section>
<section id="problem-8" class="level3">
<h3 class="anchored" data-anchor-id="problem-8">Problem 8</h3>
<ol type="a">
<li>Why does the <em>t</em>-distribution have wider tails than the normal?</li>
</ol>
<!-- -->
<ol start="2" type="A">
<li>What implication does this have on statistical testing?</li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>Because of the extra uncertainty in estimating the population SD from the sample.</p></li>
<li><p>Wider tails mean <strong>larger critical values</strong>, so you’re <strong>less likely to reject</strong> <span class="math inline">\(H_0\)</span> with small samples.</p></li>
</ol>
</details>
</section>
<section id="problem-9" class="level3">
<h3 class="anchored" data-anchor-id="problem-9">Problem 9</h3>
<p>Use Python (or something similar) to plot the density curves of <span class="math inline">\(t_3, t_{10}, t_{30}\)</span>, and standard normal.</p>
<ol type="a">
<li><p>What do you observe as df increases?</p></li>
<li><p>Which distribution has the heaviest tails?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t, norm</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="co"># x-values for plotting</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">500</span>)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot t-distributions</span></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>plt.plot(x, t.pdf(x, df<span class="op">=</span><span class="dv">3</span>), label<span class="op">=</span><span class="st">"t3"</span>, linewidth<span class="op">=</span><span class="dv">2</span>)<span class="op">;</span></span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>plt.plot(x, t.pdf(x, df<span class="op">=</span><span class="dv">10</span>), label<span class="op">=</span><span class="st">"t10"</span>)<span class="op">;</span></span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>plt.plot(x, t.pdf(x, df<span class="op">=</span><span class="dv">30</span>), label<span class="op">=</span><span class="st">"t30"</span>)<span class="op">;</span></span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot standard normal</span></span>
<span id="cb94-14"><a href="#cb94-14" aria-hidden="true" tabindex="-1"></a>plt.plot(x, norm.pdf(x), <span class="st">'r--'</span>, label<span class="op">=</span><span class="st">"N(0,1)"</span>)<span class="op">;</span></span>
<span id="cb94-15"><a href="#cb94-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-16"><a href="#cb94-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Legend and labels</span></span>
<span id="cb94-17"><a href="#cb94-17" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">"upper right"</span>)<span class="op">;</span></span>
<span id="cb94-18"><a href="#cb94-18" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Density"</span>)<span class="op">;</span></span>
<span id="cb94-19"><a href="#cb94-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"t-distributions vs. Normal distribution"</span>)<span class="op">;</span></span>
<span id="cb94-20"><a href="#cb94-20" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)<span class="op">;</span></span>
<span id="cb94-21"><a href="#cb94-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li>Heavier tails for small df. As df increases, the t-distribution converges to standard normal. This is just like we have discussed in the previous problems.</li>
</ol>
</details>
</section>
<section id="problem-10" class="level3">
<h3 class="anchored" data-anchor-id="problem-10">Problem 10</h3>
<p>Let <span class="math inline">\(Z\sim\mathcal{N}(0,1)\)</span> Use Python to compute:</p>
<ol type="a">
<li><p><span class="math inline">\(P(Z &gt; 1.96)\)</span></p></li>
<li><p><span class="math inline">\(P(-1.64 &lt; Z &lt; 1.64)\)</span></p></li>
<li><p><span class="math inline">\(P(X &gt; 120)\)</span>, if <span class="math inline">\(X \sim \mathcal{N}(100, 15^2)\)</span></p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a) "</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(<span class="fl">1.96</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a)  0.024997895148220484</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b) "</span>, stats.norm.cdf(<span class="fl">1.64</span>) <span class="op">-</span> stats.norm.cdf(<span class="op">-</span><span class="fl">1.64</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b)  0.8989948330517925</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"c) "</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(<span class="dv">120</span>, loc <span class="op">=</span> <span class="dv">100</span>, scale <span class="op">=</span> <span class="dv">15</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>c)  0.09121121972586788</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-11" class="level3">
<h3 class="anchored" data-anchor-id="problem-11">Problem 11</h3>
<p>Simulate the sample mean of 1000 samples of size 5, 30, and 100 from an exponential distribution.</p>
<ol type="a">
<li><p>Plot the histograms.</p></li>
<li><p>Comment on convergence to normality.</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to generate 1000 sample means of size n</span></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sample_means(n):</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [np.mean(np.random.exponential(scale<span class="op">=</span><span class="dv">1</span>, size<span class="op">=</span>n)) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1000</span>)]</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample sizes</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">5</span>, <span class="dv">30</span>, <span class="dv">100</span>]</span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms</span></span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, n <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes, <span class="dv">1</span>):</span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a>    plt.figure()<span class="op">;</span></span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a>    plt.hist(sample_means(n), bins<span class="op">=</span><span class="dv">30</span>, <span class="bu">range</span><span class="op">=</span>(<span class="dv">0</span>, <span class="dv">5</span>), color<span class="op">=</span><span class="st">'skyblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">'</span>)<span class="op">;</span></span>
<span id="cb101-15"><a href="#cb101-15" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">'Sample Mean'</span>)<span class="op">;</span></span>
<span id="cb101-16"><a href="#cb101-16" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">'Frequency'</span>)<span class="op">;</span></span>
<span id="cb101-17"><a href="#cb101-17" aria-hidden="true" tabindex="-1"></a>    plt.grid(<span class="va">True</span>)<span class="op">;</span></span>
<span id="cb101-18"><a href="#cb101-18" aria-hidden="true" tabindex="-1"></a>    plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-30-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-30-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-30-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li>As sample size increases, the distribution of the sample mean approaches a normal shape, even though the exponential is skewed.</li>
</ol>
</details>
</section>
<section id="problem-12" class="level3">
<h3 class="anchored" data-anchor-id="problem-12">Problem 12</h3>
<p>Generate t-statistics using normal data and see how the distribution changes.</p>
<ol type="a">
<li><p>Generate 10,000 t-statistics from n = 5, 10, 30</p></li>
<li><p>Plot and compare to standard normal</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to generate 10,000 t-statistics from samples of size n</span></span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gen_t(n):</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>    t_stats <span class="op">=</span> []</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10000</span>):</span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> np.random.normal(loc<span class="op">=</span><span class="dv">0</span>, scale<span class="op">=</span><span class="dv">1</span>, size<span class="op">=</span>n)</span>
<span id="cb102-10"><a href="#cb102-10" aria-hidden="true" tabindex="-1"></a>        t_stat <span class="op">=</span> np.mean(x) <span class="op">/</span> (np.std(x, ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(n))</span>
<span id="cb102-11"><a href="#cb102-11" aria-hidden="true" tabindex="-1"></a>        t_stats.append(t_stat)</span>
<span id="cb102-12"><a href="#cb102-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array(t_stats)</span>
<span id="cb102-13"><a href="#cb102-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-14"><a href="#cb102-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample sizes to try</span></span>
<span id="cb102-15"><a href="#cb102-15" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">30</span>]</span>
<span id="cb102-16"><a href="#cb102-16" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> [<span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">20</span>]</span>
<span id="cb102-17"><a href="#cb102-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-18"><a href="#cb102-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms and overlay standard normal density</span></span>
<span id="cb102-19"><a href="#cb102-19" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">500</span>)</span>
<span id="cb102-20"><a href="#cb102-20" aria-hidden="true" tabindex="-1"></a>normal_density <span class="op">=</span> norm.pdf(x)</span>
<span id="cb102-21"><a href="#cb102-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-22"><a href="#cb102-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n, b <span class="kw">in</span> <span class="bu">zip</span>(sample_sizes, bins):</span>
<span id="cb102-23"><a href="#cb102-23" aria-hidden="true" tabindex="-1"></a>    t_vals <span class="op">=</span> gen_t(n)<span class="op">;</span></span>
<span id="cb102-24"><a href="#cb102-24" aria-hidden="true" tabindex="-1"></a>    plt.figure()<span class="op">;</span></span>
<span id="cb102-25"><a href="#cb102-25" aria-hidden="true" tabindex="-1"></a>    plt.hist(t_vals, bins<span class="op">=</span>b, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'lightblue'</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)<span class="op">;</span></span>
<span id="cb102-26"><a href="#cb102-26" aria-hidden="true" tabindex="-1"></a>    plt.plot(x, normal_density, <span class="st">'r--'</span>, label<span class="op">=</span><span class="st">'Standard Normal'</span>)<span class="op">;</span></span>
<span id="cb102-27"><a href="#cb102-27" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f"Sampling Distribution of t-stat (n=</span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">)"</span>)<span class="op">;</span></span>
<span id="cb102-28"><a href="#cb102-28" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"t-statistic"</span>)<span class="op">;</span></span>
<span id="cb102-29"><a href="#cb102-29" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Density"</span>)<span class="op">;</span></span>
<span id="cb102-30"><a href="#cb102-30" aria-hidden="true" tabindex="-1"></a>    plt.xlim(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>)<span class="op">;</span></span>
<span id="cb102-31"><a href="#cb102-31" aria-hidden="true" tabindex="-1"></a>    plt.legend()<span class="op">;</span></span>
<span id="cb102-32"><a href="#cb102-32" aria-hidden="true" tabindex="-1"></a>    plt.grid(<span class="va">True</span>)<span class="op">;</span></span>
<span id="cb102-33"><a href="#cb102-33" aria-hidden="true" tabindex="-1"></a>    plt.show()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-32-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="4-exercises_files/figure-html/unnamed-chunk-32-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li></li>
</ol>
<p>The distribution of the <em>t</em>-statistic becomes more like the normal as n increases.</p>
</details>
</section>
<section id="problem-13" class="level3">
<h3 class="anchored" data-anchor-id="problem-13">Problem 13</h3>
<p>Compute using R:</p>
<ol type="a">
<li><p><span class="math inline">\(P(T_5 &gt; 2.015)\)</span></p></li>
<li><p><span class="math inline">\(P(|T_{10}| &gt; 2.228)\)</span></p></li>
<li><p>Interpret the meaning of the second probability in a test setting.</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li>We use the compliment to compute this case <span class="math display">\[
P(T_5&gt;2.015)=1-P(T_5\leq2.015)
\]</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a)"</span>, <span class="dv">1</span><span class="op">-</span>stats.t.cdf(<span class="fl">2.015</span>, df<span class="op">=</span><span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a) 0.0500030861634031</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Let’s simplify the expression to see qhat we’re really looking for <span class="math display">\[
P(|T_{10}|&gt;2.228)=P(T_{10}&lt;-2.228)+P(T_{10}&gt;2.228)
\]</span> Recall that like the normal distribution, the t distribution is symmetrical around its mean, which is always 0. This makes it so <span class="math display">\[
P(T&lt;-t)=P(T&gt;t)
\]</span></li>
</ol>
<p>And as such our expression becomes</p>
<p><span class="math display">\[ P(|T_{10}| &gt; 2.228) = 2\cdot P(T_{10}&lt;-2.228) \]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b) "</span>, <span class="dv">2</span> <span class="op">*</span> stats.t.cdf(<span class="op">-</span><span class="fl">2.228</span>, df<span class="op">=</span><span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b)  0.050011771817111327</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Since the probability is 5%, we can interpret the value 2.228 as the threshold (critical value) for a two-sided t-test statistic with 10 degrees of freedom for rejecting the null hypothesis. Alternatively, if we observe a test statistic of value 2.228, the p-value of the test is 5%.</li>
</ol>
</details>
</section>
<section id="problem-14" class="level3">
<h3 class="anchored" data-anchor-id="problem-14">Problem 14</h3>
<ol type="a">
<li><p>Find the z-value such that <span class="math inline">\(P(Z &lt; z) = 0.975\)</span></p></li>
<li><p>Find the z-value such that <span class="math inline">\(P(|Z| &gt; z) = 0.01\)</span></p></li>
<li><p>What is the 10th percentile of the standard normal distribution?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<p>We can find these qauntile values by using the inverse of the cumulative distribution function for the normal distribution. In practice we can often get adequaet results by using tables or use tools such as Python to calculate.</p>
<ol type="a">
<li><p><span class="math inline">\(z \approx 1.96\)</span></p></li>
<li><p>The first implication arrow comes as a consequence of the normal distribtuion being symmetric.<br>
<span class="math inline">\(P(|Z| &gt; z) = 0.01 \Rightarrow P(Z &gt; z) = 0.005 \Rightarrow z \approx 2.576\)</span></p></li>
<li><p><span class="math inline">\(z_{0.10} \approx -1.28\)</span></p></li>
</ol>
<p>Can be verified in Python:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a) "</span>, stats.norm.ppf(<span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a)  1.959963984540054</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b) "</span>, stats.norm.ppf(<span class="dv">1</span><span class="op">-</span><span class="fl">0.005</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b)  2.5758293035489004</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"c) "</span>, stats.norm.ppf(<span class="fl">0.1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>c)  -1.2815515655446004</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-15" class="level3">
<h3 class="anchored" data-anchor-id="problem-15">Problem 15</h3>
<p>Let <span class="math inline">\(X \sim \mathcal{N}(200, 30^2)\)</span>. Compute:</p>
<ol type="a">
<li><p><span class="math inline">\(P(X &gt; 240)\)</span></p></li>
<li><p><span class="math inline">\(P(160 &lt; X &lt; 220)\)</span></p></li>
<li><p>What value of <span class="math inline">\(X\)</span> cuts off the top 5%? (What would the 95%th percentile be?)</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<p>Standardize:</p>
<ol type="a">
<li><p><span class="math inline">\(Z = \frac{240 - 200}{30} = 1.33 \Rightarrow P(Z &gt; 1.33)=1-P(Z\leq 1.33) \approx 0.0918\)</span></p></li>
<li><p>Standardize both: <span class="math inline">\(Z_1 = \frac{160 - 200}{30} = -1.33\)</span>, <span class="math inline">\(Z_2 = \frac{220 - 200}{30} = 0.67\)</span> ⇒ <span class="math inline">\(P(160&lt;X&lt;240)= P(X&lt;240)-P(X&lt;160)=P(Z&lt;0.67)-P(Z&lt;-1.33) \approx 0.7486 - 0.0918 = 0.6568\)</span></p></li>
<li><p>Find <span class="math inline">\(z\)</span> for 95th percentile. Here it’s easiest to start with the 95th percentile of the standard normal distribution, <span class="math inline">\(z=1.645\)</span>. <span class="math inline">\(z = 1.645 \Rightarrow X = 200 + 1.645 \times 30 = 249.35\)</span></p></li>
</ol>
<p>Confirming with an Python script</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a)"</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(<span class="dv">240</span>, loc<span class="op">=</span><span class="dv">200</span>, scale<span class="op">=</span><span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a) 0.09121121972586788</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Gives 0.0912 due to different approximation than above</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b)"</span>, (stats.norm.cdf(<span class="dv">220</span>, loc<span class="op">=</span><span class="dv">200</span>, scale<span class="op">=</span><span class="dv">30</span>) <span class="op">-</span> </span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>stats.norm.cdf(<span class="dv">160</span>, loc<span class="op">=</span><span class="dv">200</span>, scale<span class="op">=</span><span class="dv">30</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b) 0.6562962427272092</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co">## c) First compute the quantile, then double check</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>quant<span class="op">=</span><span class="dv">200</span><span class="op">+</span><span class="fl">1.645</span><span class="op">*</span><span class="dv">30</span></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"c)"</span>, stats.norm.cdf(quant, loc<span class="op">=</span><span class="dv">200</span>, scale<span class="op">=</span><span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>c) 0.9500150944608786</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Finding the quantile can also do this more directly:</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"quant = "</span>, stats.norm.ppf(<span class="fl">0.95</span>, loc<span class="op">=</span><span class="dv">200</span>, scale<span class="op">=</span><span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>quant =  249.34560880854417</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-16" class="level3">
<h3 class="anchored" data-anchor-id="problem-16">Problem 16</h3>
<p>Let <span class="math inline">\(T \sim t_{12}\)</span>. Feel free to use either a script or table to do this. Compute:</p>
<ol type="a">
<li><p><span class="math inline">\(P(T &lt; 2.18)\)</span></p></li>
<li><p><span class="math inline">\(P(|T| &gt; 2.18)\)</span></p></li>
<li><p>The 97.5th percentile of the distribution</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a)"</span>, stats.t.cdf(<span class="fl">2.18</span>, df <span class="op">=</span> <span class="dv">12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a) 0.9750530883473195</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Two-tailed:</li>
</ol>
<p><span class="math display">\[
P(|T| &gt; 2.18) =\cdots= 2 P(T &gt; 2.18) \approx 2  (1 - 0.975) = 0.05
\]</span> We double check with R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b)"</span>, <span class="dv">2</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>stats.t.cdf(<span class="fl">2.18</span>, df<span class="op">=</span><span class="dv">12</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b) 0.04989382330536096</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>It’s obvious that we’re really close from a) and b), but let’s still use Python to approximate even more exactly.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>stats.t.ppf(<span class="fl">0.975</span>, df <span class="op">=</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.float64(2.1788128296634177)</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-17" class="level3">
<h3 class="anchored" data-anchor-id="problem-17">Problem 17</h3>
<p>Let <span class="math inline">\(Z \sim \mathcal{N}(0,1)\)</span>. Compute:</p>
<ol type="a">
<li><p><span class="math inline">\(P(Z &gt; -0.5)\)</span></p></li>
<li><p><span class="math inline">\(P(Z &lt; 0.84)\)</span></p></li>
<li><p>What percentile corresponds to <span class="math inline">\(Z = 1.28\)</span>?</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p><span class="math inline">\(P(Z &gt; -0.5) = 1 - P(Z &lt; -0.5) = 1 - 0.3085 = 0.6915\)</span></p></li>
<li><p><span class="math inline">\(P(Z &lt; 0.84) = 0.7995\)</span></p></li>
<li><p>90th percentile (verify: <code>pnorm(1.28) ≈ 0.8997</code>)</p></li>
</ol>
<p>We use Python to verify:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a)"</span>, <span class="dv">1</span><span class="op">-</span>stats.norm.cdf(<span class="op">-</span><span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a) 0.6914624612740131</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b)"</span>, stats.norm.cdf(<span class="fl">0.84</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b) 0.7995458067395503</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co">## c) We have the z value, and we want to know what percentle it is. I.e. whats P(Z&lt;1.28)</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"c)"</span>, stats.norm.cdf(<span class="fl">1.28</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>c) 0.8997274320455579</code></pre>
</div>
</div>
</details>
</section>
<section id="problem-18" class="level3">
<h3 class="anchored" data-anchor-id="problem-18">Problem 18</h3>
<p>Let <span class="math inline">\(Z \sim \mathcal{N}(0,1)\)</span> and <span class="math inline">\(T \sim t_5\)</span></p>
<ol type="a">
<li><p>Compute the density <span class="math inline">\(f_Z(1)\)</span></p></li>
<li><p>Compute the density <span class="math inline">\(f_T(1)\)</span></p></li>
<li><p>Compare and interpret</p></li>
</ol>
<details>
<summary>
Show solution
</summary>
<p>a), b) For densitiy functions in Python we use stats.norm.pdf and stats.t.pdf to compute their values. Since the df is pretty low here, we can expect some difference between the standard normal and the t distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"a) Normal:"</span>, stats.norm.pdf(<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>a) Normal: 0.24197072451914337</code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b) T with 5 degrees of freedom:"</span>, stats.t.pdf(<span class="dv">1</span>, df<span class="op">=</span><span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>b) T with 5 degrees of freedom: 0.21967979735098053</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>The t-distribution has heavier tails, so at z = 1, its peak is slightly lower than that of the standard normal. The tails decay more slowly.</li>
</ol>


</details></section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./4-python.html" class="pagination-link" aria-label="Python">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Python</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./5-intro.html" class="pagination-link" aria-label="Introduction">
        <span class="nav-page-text">Introduction</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>